- lua/astrocommunity/pack/rust/rust.lua
i guess it still needs some changes
> feat(pack) add rust

- README.md
- lua/astrocommunity/completion/copilot-lua-cmp/copilot-lua-cmp.lua
- lua/astrocommunity/completion/copilot-lua/copilot-lua.lua
- lua/astrocommunity/pack/go/go.lua
Fixes some small issues and updates the README with the new categories
Resolves #15
> Small Cleanup

- lua/astrocommunity/color/tint-nvim/tint-nvim.lua
- lua/astrocommunity/colorscheme/everforest/everforest.lua
- lua/astrocommunity/colorscheme/rose-pine/rose-pine.lua
- lua/astrocommunity/completion/copilot-lua/copilot-lua.lua
- lua/astrocommunity/diagnostics/trouble-nvim/trouble-nvim.lua
- lua/astrocommunity/media/drop-nvim/drop-nvim.lua
- lua/astrocommunity/media/pets-nvim/pets-nvim.lua
- lua/astrocommunity/media/presence-nvim/presence-nvim.lua
- lua/astrocommunity/media/vim-wakatime/vim-wakatime.lua
- lua/astrocommunity/motion/mini-bracketed/mini-bracketed.lua
- lua/astrocommunity/scrolling/mini-animate/mini-animate.lua
- lua/astrocommunity/scrolling/satellite-nvim/satellite-nvim.lua
This does some code simplification, improves the colorscheme loading of `everforest` and adds `rose-pine`
> chore: various code cleanup

- README.md
- lua/astrocommunity/bars-and-lines/scope-nvim/scope-nvim.lua
- lua/astrocommunity/bars-and-lines/smartcolumn-nvim/smartcolumn-nvim.lua
- lua/astrocommunity/code-runner/overseer-nvim/overseer-nvim.lua
- lua/astrocommunity/color/ccc-nvim/ccc-nvim.lua
- lua/astrocommunity/comment/mini-comment/mini-comment.lua
- lua/astrocommunity/debugging/nvim-bqf/nvim-bqf.lua
- lua/astrocommunity/diagnostics/lsp_lines-nvim/lsp_lines-nvim.lua
- lua/astrocommunity/editing-support/refactoring-nvim/refactoring-nvim.lua
- lua/astrocommunity/editing-support/zen-mode-nvim/zen-mode-nvim.lua
- lua/astrocommunity/markdown-and-latex/glow-nvim/glow-nvim.lua
- lua/astrocommunity/note-taking/neorg/neorg.lua
- lua/astrocommunity/project/neoconf-nvim/neoconf-nvim.lua
Need to do a few more and update the README categories
> More plugin additions

- README.md
it's by far not perfect. but we need more info in the readme
> fix(readme): update the README.md 

- lua/astrocommunity/editing-support/nvim-regexplainer/README.md
- lua/astrocommunity/editing-support/nvim-regexplainer/nvim-regexplainer.lua
Added a minimal configuration of Regexplainer. Unfortunately the Regexplainer Toggle does not work properly at the moment but it's nothing that I can fix on my side.
> Added regexplainer

- lua/astrocommunity/pack/python/python.lua
if only 1 entry is added table.insert is faster then list_extend
> fix(pack): using table.insert instead of list_extend on python dap

- lua/astrocommunity/bars-and-lines/smartcolumn-nvim/smartcolumn-nvim.lua
- lua/astrocommunity/color/ccc-nvim/ccc-nvim.lua
- lua/astrocommunity/color/tint-nvim/tint-nvim.lua
- lua/astrocommunity/comment/mini-comment/mini-comment.lua
- lua/astrocommunity/completion/copilot-lua-cmp/copilot-lua-cmp.lua
- lua/astrocommunity/completion/copilot-lua/copilot-lua.lua
- lua/astrocommunity/editing-support/refactoring-nvim/refactoring-nvim.lua
- lua/astrocommunity/indent/indent-blankline-nvim/indent-blankline-nvim.lua
- lua/astrocommunity/indent/mini-indentscope/mini-indentscope.lua
- lua/astrocommunity/media/vim-wakatime/vim-wakatime.lua
- lua/astrocommunity/motion/mini-ai/mini-ai.lua
- lua/astrocommunity/motion/mini-basics/mini-basics.lua
- lua/astrocommunity/motion/mini-bracketed/mini-bracketed.lua
- lua/astrocommunity/scrolling/satellite-nvim/satellite-nvim.lua
Updates to the latest changes in AstroNvim v3 from https://github.com/AstroNvim/AstroNvim/commit/41db48682757dc06b7ea07ab4e29664601a8d4e0
> fix: update to new user event based file lazy loading

- lua/astrocommunity/color/ccc-nvim/ccc-nvim.lua
fixes https://github.com/AstroNvim/astrocommunity/issues/51
> fix(ccc): correct module path for highlighter

- lua/astrocommunity/editing-support/nvim-regexplainer/nvim-regexplainer.lua
- lua/astrocommunity/pack/bash/bash.lua
- lua/astrocommunity/pack/go/go.lua
- lua/astrocommunity/pack/json/json.lua
- lua/astrocommunity/pack/julia/julia.lua
- lua/astrocommunity/pack/lua/lua.lua
- lua/astrocommunity/pack/nix/nix.lua
- lua/astrocommunity/pack/python/python.lua
- lua/astrocommunity/pack/rust/rust.lua
- lua/astrocommunity/pack/typescript/typescript.lua
- lua/astrocommunity/utility/noice-nvim/noice-nvim.lua
- lua/astrocommunity/utils.lua
This utility function fixes some issues when it comes to using multiple packs at the same time that might provide the same language servers/linters/formatters/etc.
> refactor: add utilities to easily insert/extend lists with unique values

- lua/astrocommunity/indent/indent-blankline-nvim/README.md
Just swapped around the words to fix a grammar issue.
> fix: sentence structure

- lua/astrocommunity/pack/tailwindcss/README.md
- lua/astrocommunity/pack/tailwindcss/tailwindcss.lua
I really hope the ci doesn't scream at me again.
> feat(pack): add tailwindcss pack

- lua/astrocommunity/pack/tailwindcss/tailwindcss.lua
> fix(pack/tailwindcss): colorize for nvim-colorizer

- lua/astrocommunity/pack/julia/README.md
- lua/astrocommunity/pack/julia/julia.lua
- lua/astrocommunity/pack/rust/README.md
- lua/astrocommunity/pack/rust/rust.lua
- lua/astrocommunity/pack/toml/README.md
- lua/astrocommunity/pack/toml/toml.lua
- lua/astrocommunity/pack/typescript/README.md
- lua/astrocommunity/pack/typescript/typescript.lua
> refactor(pack): simplify language packs with multiple languages

- lua/astrocommunity/pack/json/README.md
- lua/astrocommunity/pack/json/json.lua
- lua/astrocommunity/pack/markdown/README.md
- lua/astrocommunity/pack/markdown/markdown.lua
- lua/astrocommunity/pack/tailwindcss/README.md
- lua/astrocommunity/pack/tailwindcss/tailwindcss.lua
- lua/astrocommunity/pack/typescript/README.md
- lua/astrocommunity/pack/typescript/typescript.lua
- lua/astrocommunity/pack/yaml/README.md
- lua/astrocommunity/pack/yaml/yaml.lua
As per null-ls README: https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#notes-36
> feat(pack): use prettierd instead of prettier

- lua/astrocommunity/editing-support/text-case-nvim/README.md
- lua/astrocommunity/editing-support/text-case-nvim/text-case-nvim.lua
Title pretty much says it all.
Couple of thoughts before I mark this as a non-draft.
Should be bind this to a key?
And, the event, perhaps we instead should load it on CMD instead of on a real file?
> feat(editing-support): Add text-case.nvim

- lua/astrocommunity/code-runner/sniprun/README.md
- lua/astrocommunity/code-runner/sniprun/sniprun.lua
Added initial version of sniprun.
> feat(code-runner): Add sniprun

- lua/astrocommunity/pack/dart/README.md
- lua/astrocommunity/pack/dart/dart.lua
- Adds `dart` ands `yaml` treesitter parsers
- Adds `dartls` language server
- Adds `flutter-tools.nvim` for language specific tooling
> feat(pack): add dart

- README.md
adding information to read the astronvim readme
> chore(main): Update README.md

- lua/astrocommunity/motion/harpoon/README.md
- lua/astrocommunity/motion/harpoon/harpoon.lua
Unsure about how much the terminal navigation is used, I heavily used the file navigation and figured a first PR for this would be fair enough.
> feat: add harpoon

- lua/astrocommunity/colorscheme/poimandres/README.md
- lua/astrocommunity/colorscheme/poimandres/poimandres.lua
Add the poimandres Neovim theme.
> feat(colorscheme): add poimandres

- lua/astrocommunity/colorscheme/dracula/README.md
- lua/astrocommunity/colorscheme/dracula/dracula.lua
add dracula colorscheme for neovim written in Lua
> feat(colorscheme): add dracula

- lua/astrocommunity/colorscheme/monokai-pro/README.md
- lua/astrocommunity/colorscheme/monokai-pro/monokai-pro.lua
Adds the [`monokai-pro`](https://github.com/loctvl842/monokai-pro.nvim) colorscheme.
> feat(colorscheme): add monokai-pro

- lua/astrocommunity/editing-support/nvim-regexplainer/nvim-regexplainer.lua
- lua/astrocommunity/pack/astro/astro.lua
- lua/astrocommunity/pack/bash/bash.lua
- lua/astrocommunity/pack/cmake/cmake.lua
- lua/astrocommunity/pack/dart/dart.lua
- lua/astrocommunity/pack/go/go.lua
- lua/astrocommunity/pack/haskell/haskell.lua
- lua/astrocommunity/pack/haxe/haxe.lua
- lua/astrocommunity/pack/java/java.lua
- lua/astrocommunity/pack/json/json.lua
- lua/astrocommunity/pack/julia/julia.lua
- lua/astrocommunity/pack/lua/lua.lua
- lua/astrocommunity/pack/markdown/markdown.lua
- lua/astrocommunity/pack/nix/nix.lua
- lua/astrocommunity/pack/php/php.lua
- lua/astrocommunity/pack/prisma/prisma.lua
- lua/astrocommunity/pack/python/python.lua
- lua/astrocommunity/pack/rust/rust.lua
- lua/astrocommunity/pack/svelte/svelte.lua
- lua/astrocommunity/pack/tailwindcss/tailwindcss.lua
- lua/astrocommunity/pack/toml/toml.lua
- lua/astrocommunity/pack/typescript-deno/typescript.lua
- lua/astrocommunity/pack/typescript/typescript.lua
- lua/astrocommunity/pack/vue/vue.lua
- lua/astrocommunity/pack/yaml/yaml.lua
- lua/astrocommunity/utility/noice-nvim/noice-nvim.lua
Relies on https://github.com/AstroNvim/AstroNvim/pull/1843 and release of AstroNvim v3.13.1
> refactor: simplify list_insert_unique usages

- lua/astrocommunity/git/openingh/README.md
- lua/astrocommunity/git/openingh/openingh.lua
To opens the current file or project page in GitHub easily.
> feat(git): add openingh

- lua/astrocommunity/pack/haskell/haskell.lua
Relies on https://github.com/jay-babu/mason-nvim-dap.nvim/pull/88
> feat(pack): enable automatic install of haskell dap

- lua/astrocommunity/pack/docker/README.md
- lua/astrocommunity/pack/docker/docker.lua
Created docker folder inside pack. Added dockerfile-language-server and docker-compose-language-service language servers for LSP and hadolint for linting support of dockerfile and docker-compose file.
> feat(pack): added docker pack

- lua/astrocommunity/pack/docker/docker.lua
> fix(pack): fixed docker pack

- lua/astrocommunity/pack/terraform/README.md
- lua/astrocommunity/pack/terraform/terraform.lua
added terraform lsp and linter
> feat(pack): added terraform pack

- lua/astrocommunity/pack/python/README.md
> docs: Update pack.python README.md

- lua/astrocommunity/motion/nvim-spider/README.md
- lua/astrocommunity/motion/nvim-spider/nvim-spider.lua
This does not include the subword text obect that could be included via [nvim-various-textobjs](https://github.com/chrisgrieser/nvim-various-textobjs).
> feat(motion): Add nvim-spider

- lua/astrocommunity/pack/lua/README.md
- lua/astrocommunity/pack/lua/lua.lua
Personally I'm a big fan of `selene` so I think it should be part of the pack.
> feat(pack): add selene linter to lua pack

- lua/astrocommunity/pack/python/python.lua
Ruff already to the pylint's job but faster.
> chore(pack): remove pylint

- lua/astrocommunity/colorscheme/gruvbox-nvim/README.md
> fix(gruvbox): readme on configuration

- lua/astrocommunity/color/twilight-nvim/twilight-nvim.lua
Opinions on including keymaps in these community plugins?
> refactor(twilight): update lazy loading and add default keymap

- lua/astrocommunity/pack/dart/dart.lua
> fix(dart): fix dart pack

- lua/astrocommunity/completion/tabnine-nvim/README.md
- lua/astrocommunity/completion/tabnine-nvim/tabnine.lua
> feat(completion): add tabnine-nvim

- lua/astrocommunity/code-runner/compiler-nvim/README.md
- lua/astrocommunity/code-runner/compiler-nvim/compiler-nvim.lua
More info about the project can be found here: https://github.com/Zeioth/Compiler.nvim
> feat(code-runner): add compiler.nvim

- lua/astrocommunity/motion/harpoon/init.lua
> fix(harpoon)!: fix mapping that conflicts with core mapping

- lua/astrocommunity/pack/python/init.lua
This was raised on Discord https://discord.com/channels/939594913560031363/1122143513912561745
https://beta.ruff.rs/docs/faq/#which-tools-does-ruff-replace
> refactor(python): Remove isort in favor of ruff_lsp

- lua/astrocommunity/pack/python/init.lua
add python debug with arguments
> feat: add python debug with arguments

- lua/astrocommunity/pack/typescript/init.lua
Reverts AstroNvim/astrocommunity#319
> revert: "feat: add astro filetype to eslint_d handler in typescript pack"

- lua/astrocommunity/pack/go/README.md
- lua/astrocommunity/pack/go/init.lua
[`ray-x/go.nvim`](https://github.com/ray-x/go.nvim) provide more powerful functions
> feat: change olexsmir/gopher.nvim to ray-x/go.nvim

- lua/astrocommunity/pack/rust/README.md
> docs(pack): Add section for possible LSP tweaks to Rust

- lua/astrocommunity/editing-support/vim-move/README.md
- lua/astrocommunity/editing-support/vim-move/init.lua
[`vim-move`](https://github.com/matze/vim-move) provides the ability to move blocks of code
> feat(editing-support): add vim-move plugin

- lua/astrocommunity/color/ccc-nvim/init.lua
add default nvim command of ccc-nvim.
> feat(color): add default nvim command of ccc-nvim.

- lua/astrocommunity/workflow/hardtime-nvim/init.lua
> fix(hardtime-nvim): config uses legacy table

- lua/astrocommunity/pack/html-css/README.md
- lua/astrocommunity/pack/html-css/init.lua
add emmet_ls to html-css supprt syntax like `li * 5`
> feat(html-css): add emmet_ls to html-css supprt syntax like `li * 5`

- lua/astrocommunity/file-explorer/mini-files/README.md
- lua/astrocommunity/file-explorer/mini-files/init.lua
> feat(file-explorer): Add initial support for mini.files

- lua/astrocommunity/scrolling/nvim-scrollbar/init.lua
> fix(nvim-scrollbar): Fix issue with is_available calls

- lua/astrocommunity/colorscheme/helix-nvim/README.md
- lua/astrocommunity/colorscheme/helix-nvim/init.lua
Adding my implementation of Helix Editor's default theme for Neovim.
> feat(colorscheme): add helix-nvim

- lua/astrocommunity/editing-support/multicursors-nvim/README.md
- lua/astrocommunity/editing-support/multicursors-nvim/init.lua
Adds multicursors.nvim plugin for multi cursor editing support.
> feat(editing-support): add multicursors.nvim plugin

- lua/astrocommunity/editing-support/telescope-undo-nvim/init.lua
Is `chore` the correct opt here?
> feat(telescope-undo-nvim): add `<leader>fu` keybind

- lua/astrocommunity/motion/grapple-nvim/init.lua
This is definetly not a copy of #376
> fix(grapple-nvim): Make which-key entry color blue, as it should be

- lua/astrocommunity/pack/haxe/init.lua
> fix(haxe): fix treesitter detection for haxe

- lua/astrocommunity/editing-support/neogen/init.lua
- lua/astrocommunity/git/neogit/init.lua
- lua/astrocommunity/motion/mini-surround/init.lua
This PR fixes remaining plugins with wrong which-key colors
> fix: Make which-key entry color blue, as it should be

- lua/astrocommunity/test/neotest/init.lua
> fix(neotest): add neodev integration

- lua/astrocommunity/git/neogit/init.lua
Add config setup to setup neogit so it runs
> fix(neogit): Need to setup neogit before it runs

- lua/astrocommunity/motion/marks-nvim/README.md
- lua/astrocommunity/motion/marks-nvim/init.lua
add marks.nvim improve nvim mark function
> feat(motion): add marks.nvim improve nvim mark function

- lua/astrocommunity/editing-support/comment-box-nvim/init.lua
> fix(comment-box-nvim): Load on User AstroFile event

- lua/astrocommunity/editing-support/nvim-treesitter-endwise/README.md
- lua/astrocommunity/editing-support/nvim-treesitter-endwise/init.lua
Following this issue https://github.com/AstroNvim/astrocommunity/issues/155
> feat(editing-support): add treesitter endwise

- lua/astrocommunity/utility/nvim-toggler/init.lua
plugin nvim-toggler keys tip toggle cursorword
> fix(nvim-toggler): add lazy load on keys

- lua/astrocommunity/colorscheme/catppuccin/init.lua
> fix(catppuccin): add recommended telescope config

- lua/astrocommunity/motion/vim-matchup/init.lua
> feat(vim-matchup): improve offscreen popup style

- lua/astrocommunity/pack/php/README.md
- lua/astrocommunity/pack/php/init.lua
> feat(php): Add `php-cs-fixer` as formatter for php

- lua/astrocommunity/editing-support/yanky-nvim/README.md
- lua/astrocommunity/editing-support/yanky-nvim/init.lua
Adds [yanky.nvim](https://github.com/gbprod/yanky.nvim) plugin for improved Improved yank and put functionalities.
> feat(editing-support): add yanky.nvim

- lua/astrocommunity/editing-support/refactoring-nvim/init.lua
mappings. based on https://github.com/ThePrimeagen/refactoring.nvim
> fix(refactoring-nvim): add select mode to mappings. remove conflicting

- lua/astrocommunity/completion/copilot-lua-cmp/init.lua
Reverts AstroNvim/astrocommunity#491
fixes https://github.com/AstroNvim/astrocommunity/issues/497
> fix(copilot-lua-cmp): revert #491

- lua/astrocommunity/utility/noice-nvim/init.lua
> fix(noice-nvim): detect inc_rename and enable

- lua/astrocommunity/editing-support/refactoring-nvim/init.lua
Lazy loads [refactoring.nvim](https://github.com/ThePrimeagen/refactoring.nvim) on the `Refactor` command
None
> fix(refactoring-nvim): lazy load on `Refactor` cmd

- lua/astrocommunity/pack/cue/README.md
- lua/astrocommunity/pack/cue/init.lua
> feat(pack): Add cue language pack

- lua/astrocommunity/workflow/hardtime-nvim/init.lua
> fix(hardtime-nvim): disable hardtime-nvim on dressing-nvim fts

- lua/astrocommunity/workflow/hardtime-nvim/init.lua
> fix(hardtime-nvim): disable hardtime-nvim on mini.files

- lua/astrocommunity/pack/zig/README.md
- lua/astrocommunity/pack/zig/init.lua
I'm slowly moving away from GitHub and so I will archive all my Neovim-related code here. Updated the `zig-tools.nvim` plugin links to point the new maintained url
> feat(pack): update Zig url

- lua/astrocommunity/colorscheme/neosolarized-nvim/init.lua
> fix(neosolarized-nvim): Add missing dependencies

- lua/astrocommunity/completion/copilot-lua-cmp/init.lua
Import copilot from another place to reduce duplicate logic.
> chore(completion): de-duplicate copilot logic

- lua/astrocommunity/editing-support/nvim-devdocs/init.lua
V4 compatibility fix for the v4 branch of astrocommunity for the devdocs plugin.
> fix(devdocs): V4 compatibility fix for devdocs

- lua/astrocommunity/indent/indent-blankline-nvim/init.lua
Since the new version of the indent-blankline plugin, the configuration syntax changes. Here the new syntax to do the same configuration.
> fix(indent-blankline-nvim): Fix indent-blankline-nvim configuration to match the new plugin requirements

- lua/astrocommunity/pack/typescript/init.lua
> fix(typescript): Check for deprecated .eslintrc file

- README.md
- lua/astrocommunity/pack/typescript/init.lua
Optimized the README's structure to improve alignment, layout, and overall readability. This ensures a more polished and professional presentation for the AstroNvim community.
No breaking changes were introduced. The main goal was to enhance the presentation of the existing content without altering the core information.
> docs: Update README for enhanced user experience

- lua/astrocommunity/pack/swift/README.md
> docs(swift): Improve documentation

- lua/astrocommunity/pack/python-ruff/README.md
- lua/astrocommunity/pack/python-ruff/init.lua
> feat(pack)!: Split python pack into python and python-ruff

- lua/astrocommunity/pack/thrift/README.md
- lua/astrocommunity/pack/thrift/init.lua
> feat(pack): add thrift pack

- lua/astrocommunity/pack/cpp/init.lua
> feat(cpp): Remove clang-format due to clangd also providing formatting

- lua/astrocommunity/editing-support/stickybuf-nvim/README.md
- lua/astrocommunity/editing-support/stickybuf-nvim/init.lua
> feat(editing-support): add stickybuf.nvim

- lua/astrocommunity/utility/noice-nvim/init.lua
This PR enables noice on neovide. 
Closes #617
> fix(noice-nvim): Remove conditional, enabling noice on neovide

- lua/astrocommunity/pack/helm/init.lua
Fix helm pack misconfiguration causing an error during `:TSUpdate`
> fix(helm): Fix helm pack misconfiguration

- lua/astrocommunity/colorscheme/mini-base16/README.md
This PR corrects the typo of `Repsoitory` on `Readme.md`
> docs(mini-base16): fix typo

- lua/astrocommunity/pack/typescript/init.lua
This PR adds the `.mjs` extension to the `has_prettier` function in TypeScript pack. This extension is supported by Prettier ([docs here](https://prettier.io/docs/en/configuration.html)).
> feat(typescript): Add .mjs files to Prettier detection helper func

- lua/astrocommunity/lsp/garbage-day-nvim/README.md
- lua/astrocommunity/lsp/garbage-day-nvim/init.lua
Garbage collector that stops inactive LSP clients to free RAM.
> feat(lsp): Add garbage-day.nvim

- lua/astrocommunity/color/transparent-nvim/init.lua
Added processing of BufferLine, lualine
> refactor(transparent-nvim): Replace opts table with config

- lua/astrocommunity/motion/hop-nvim/init.lua
> fix(hop-nvim): Change remote to maintained fork 

- lua/astrocommunity/pack/rust/init.lua
> fix(rust): typo in lsp settings

- lua/astrocommunity/note-taking/zk-nvim/README.md
- lua/astrocommunity/note-taking/zk-nvim/init.lua
Adding support for zk-nvim.
All about Zettelkasten here: https://zettelkasten.de/posts/overview/
> feat(note-taking): add support for zettelkasten with zk-nvim

- lua/astrocommunity/pack/rust/README.md
> docs(rust): add guide on how to format with clippy

- lua/astrocommunity/pack/cpp/init.lua
- fix clangd not working ad default
> fix(cpp): enable clangd handler

- lua/astrocommunity/git/gist-nvim/README.md
- lua/astrocommunity/git/gist-nvim/init.lua
Adding gist-nvim. Pretty neat gist creation and editing tool
this one is specific to GitHub tho, as it relies on the `gh` command line tool.
> feat(git): Add gist-nvim

- lua/astrocommunity/editing-support/wildfire-nvim/README.md
- lua/astrocommunity/editing-support/wildfire-nvim/init.lua
Adds [wildfire.nvim](https://github.com/SUSTech-data/wildfire.nvim), smart selection of the closest text object. A modern successor to [wildfire.vim](https://github.com/gcmt/wildfire.vim), empowered with the
superpower of treesitter.
> feat(editing-support): add wildfire.nvim

- lua/astrocommunity/pack/gleam/README.md
- lua/astrocommunity/pack/gleam/init.lua
Adds a language pack for the [gleam](https://gleam.run) language.
> feat(pack): gleam pack

- lua/astrocommunity/pack/crystal/README.md
- lua/astrocommunity/pack/crystal/init.lua
Adds an language pack for the [Crystal](https://crystal-lang.org) programming language.
> feat(pack): Add crystal pack

- lua/astrocommunity/editing-support/todo-comments-nvim/init.lua
Adds lazy load `todo-comments` on command.
> fix(todo-comments-nvim): Lazy load todo-comments on command

- lua/astrocommunity/pack/just/init.lua
> fix(just): Fix buggy just pack

- lua/astrocommunity/pack/helm/init.lua
> fix(helm): Swap to correct branch

- lua/astrocommunity/motion/tabout-nvim/README.md
- lua/astrocommunity/motion/tabout-nvim/init.lua
This adds the [tabout.nvim](https://github.com/abecodes/tabout.nvim) plugin
> feat(motion): add tabout.nvim

- lua/astrocommunity/motion/harpoon/init.lua
Closes #721 
Changes made in init.lua file in harpoon plugin.
> fix(harpoon): change word terminal to term

- lua/astrocommunity/pack/docker/init.lua
> fix(docker): missing `list_insert_unique` breaking change

- lua/astrocommunity/editing-support/conform-nvim/README.md
- lua/astrocommunity/editing-support/conform-nvim/init.lua
Adds conform.nvim as an option for users to configure as the formatting plugin in AstroNvim
> feat(editing-support): add `conform.nvim`

- lua/astrocommunity/git/openingh-nvim/init.lua
Added mappings to copy urls to clipboard
> feat(openingh-nvim): added mappings to copy url

- lua/astrocommunity/pack/nix/init.lua
[rnix](https://github.com/nix-community/rnix-lsp) is archived and unmantained for a while now, also hasnt been working for me.
> feat(nix): replace rnix with nil_ls

- lua/astrocommunity/pack/pkl/README.md
- lua/astrocommunity/pack/pkl/init.lua
This adds support for the new Pkl language from Apple.
> feat(pack): add Pkl language support

- lua/astrocommunity/debugging/nvim-chainsaw/README.md
- lua/astrocommunity/debugging/nvim-chainsaw/init.lua
> feat(debugging): Add nvim-chainsaw

- lua/astrocommunity/editing-support/cloak-nvim/README.md
- lua/astrocommunity/editing-support/cloak-nvim/init.lua
Unsure about the folder Ive added it under.
> feat(editing-support): Add cloak.nvim

- lua/astrocommunity/pack/java/README.md
Will fix one of the issues raised in #183.
I think we can go ahead and close that issue after me amend the contrib guide, any thoughts? @mehalter
> docs(java): Add note about root pattern

- lua/astrocommunity/pack/rust/README.md
Hope this helps someone else!
Closes #766
> docs(rust): Fix guide on how to use clippy instead of cargo check on save

- lua/astrocommunity/colorscheme/nord-nvim/init.lua
- lua/astrocommunity/colorscheme/sonokai/init.lua
- lua/astrocommunity/editing-support/conform-nvim/init.lua
- lua/astrocommunity/git/gist-nvim/init.lua
- lua/astrocommunity/indent/mini-indentscope/init.lua
- lua/astrocommunity/lsp/lsp-inlayhints-nvim/init.lua
- lua/astrocommunity/markdown-and-latex/vimtex/init.lua
- lua/astrocommunity/motion/leap-nvim/init.lua
- lua/astrocommunity/motion/vim-matchup/init.lua
- lua/astrocommunity/pack/clojure/init.lua
- lua/astrocommunity/pack/cpp/init.lua
- lua/astrocommunity/pack/full-dadbod/init.lua
- lua/astrocommunity/pack/rust/init.lua
- lua/astrocommunity/scrolling/mini-animate/init.lua
- lua/astrocommunity/search/nvim-hlslens/init.lua
- lua/astrocommunity/split-and-window/minimap-vim/init.lua
- lua/astrocommunity/split-and-window/windows-nvim/init.lua
- lua/astrocommunity/startup/fsplash-nvim/init.lua
- lua/astrocommunity/terminal-integration/nvim-unception/README.md
- lua/astrocommunity/terminal-integration/nvim-unception/init.lua
This does more of the refactor to utilize AstroCore features throughout the entries in AstroCommunity. Configuring things like autocommands and options that expose them to the user to actually be configured.
_Note:_ This hasn't been fully tested and needs to be looked at pretty closely before merging to make sure this doesn't break anything. Most of this was done through vim macros.
Once approved and everything I will handle doing a merge with rebase so we don't lose all the different commits and changelog entries.
> More AstroCore refactoring

- lua/astrocommunity/pack/nix/README.md
Updated README.md after LSP change in #737 
Code got updated, readme didn't
> docs(nix): Update README.md after LSP change

- lua/astrocommunity/recipes/neovide/README.md
- lua/astrocommunity/recipes/neovide/init.lua
Adds a functionallity for neovide for changing the scale factor, via user commands and keybinds.
> feat(recipes): add neovide

- lua/astrocommunity/lsp/coc-nvim/init.lua
Pre-install `coc-json` for Coc configuration, which comes with its own completion source.
> feat(coc): add json for coc configuration

- lua/astrocommunity/lsp/coc-nvim/init.lua
Add coc-marketplace to be pre-installed; this is similar to, e.g., Mason, where users can easily navigate, find, and install Coc adapters/linter, and more.
> feat(coc): add marketplace

- lua/astrocommunity/editing-support/vim-visual-multi/README.md
- lua/astrocommunity/editing-support/vim-visual-multi/init.lua
Add vim-visual-multi which is a multiple cursors plugin for vim/neovim.
https://github.com/mg979/vim-visual-multi
> feat(editing-support): add vim-visual-multi

- lua/astrocommunity/keybinding/mini-clue/README.md
- lua/astrocommunity/keybinding/mini-clue/init.lua
> feat(keybinding): Add mini.clue

- lua/astrocommunity/keybinding/mini-clue/init.lua
Add built-in windows submode to mini.clue
> feat(mini.clue): add windows submode

- lua/astrocommunity/diagnostics/lsp_lines-nvim/init.lua
`virtual_text` moved from astrolsp to astrocore
fix #825
> fix(lsp_lines-nvim): change virtual_text option to astrocore

- lua/astrocommunity/pack/elixir-phoenix/README.md
- lua/astrocommunity/pack/elixir-phoenix/init.lua
There's a fair amount of interest in using AstroNvim for Elixir/Phoenix projects, see: https://elixirforum.com/t/getting-heex-and-h-working-in-nvim-with-astronvim for a bit more context. It would be nice to have a single thing people can use that gives them everything they need. Most stuff works out of the box, there's just a tiny bit of missing config.
> feat(pack): add elixir/phoenix pack

- lua/astrocommunity/media/codesnap-nvim/README.md
- lua/astrocommunity/media/codesnap-nvim/init.lua
Adds [CodeSnap.nvim](https://github.com/mistricky/codesnap.nvim) plugin with some default bindings
> feat(media): add codesnap.nvim

- lua/astrocommunity/completion/mini-completion/init.lua
> fix(mini-completion): Disable all cmp plugins

- lua/astrocommunity/diagnostics/error-lens-nvim/README.md
- lua/astrocommunity/diagnostics/error-lens-nvim/init.lua
R? @AstroNvim/astrocommunity-maintainers
> feat(diagnostics): Add error-lens.nvim

- lua/astrocommunity/editing-support/rainbow-delimiters-nvim/init.lua
- lua/astrocommunity/editing-support/true-zen-nvim/init.lua
- lua/astrocommunity/editing-support/vim-move/init.lua
- lua/astrocommunity/lsp/garbage-day-nvim/init.lua
- lua/astrocommunity/lsp/lsp-inlayhints-nvim/init.lua
Noticed some lazy loading improvements from my personal config. These were the one i am using, sorry but i cannot check all plugins, i hope i can improve the startup/running performance a tiny bit further.
> perf: set appropiate/missing lazy loading events

- lua/astrocommunity/keybinding/nvcheatsheet-nvim/README.md
- lua/astrocommunity/keybinding/nvcheatsheet-nvim/init.lua
This adds the [nvcheatsheet.nvim](https://github.com/smartinellimarco/nvcheatsheet.nvim) plugin
> feat(keybinding): add `nvcheatsheet.nvim`

- lua/astrocommunity/motion/harpoon/init.lua
replaced deprecated function `append` with updated function `add`.
> fix(harpoon): deprecated function in configuration

- lua/astrocommunity/editing-support/cloak-nvim/init.lua
fix: #884
i guess there is no better solution.
> fix(cloak-nvim): Fix event

- lua/astrocommunity/completion/fittencode-nvim/README.md
- lua/astrocommunity/completion/fittencode-nvim/init.lua
Closes #895
Adds fitten code ai assistant with inline completion mode
> feat(completion): added fitten

- lua/astrocommunity/completion/fittencode-nvim/README.md
- lua/astrocommunity/pack/typst/README.md
- lua/astrocommunity/pack/typst/init.lua
Adds preview support for typst through [typst-preview.nvim](https://github.com/chomosuke/typst-preview.nvim)
> feat(typst): added typst-preview.nvim plugin support

- lua/astrocommunity/completion/fittencode-nvim/README.md
- lua/astrocommunity/motion/harp-nvim/README.md
- lua/astrocommunity/motion/harp-nvim/harp-nvim.lua
Added a quick plugin setup to utilize Harp (https://github.com/Axlefublr/harp) without needing to modify init.lua for nvim itself.
> feat(motion): Added harp.nvim plugin

- lua/astrocommunity/editing-support/nvim-devdocs/init.lua
Support [DevdocsToggle](https://github.com/luckasRanarison/nvim-devdocs/issues/67)
Fix [focus issue](https://github.com/luckasRanarison/nvim-devdocs/issues/73)
> fix(nvim-devdocs): focus float and toggle

- lua/astrocommunity/pack/zig/README.md
- lua/astrocommunity/pack/zig/init.lua
Added neotest support for Zig
Do we need zig-tools.nvim ? Last activity was 2 years ago, so maybe we can safely remove it ?
> feat(zig): add neotest support for zig

- lua/astrocommunity/pack/dart/init.lua
- lua/astrocommunity/pack/typst/init.lua
This changes the way some optional plugins so they don't load as dependency
> fix(dart): correct optional plugins loading

- lua/astrocommunity/debugging/persistent-breakpoints-nvim/init.lua
> fix(persistent-breakpoints-nvim): remove unnecessary code

- lua/astrocommunity/pack/zig/init.lua
Neotest-zig doesn't have any branches.
> fix(pack): remove non-existant branch

- lua/astrocommunity/lsp/coc-nvim/init.lua
> fix(coc-nvim): disable heirline coc_status update

- lua/astrocommunity/media/codesnap-nvim/init.lua
Adds keymaps for taking code snapshots with highlights.
> feat(codesnap-nvim): add keymaps for snapshots with highlight

- lua/astrocommunity/lsp/coc-nvim/init.lua
> feat(coc-nvim): add catppuccin integration

- lua/astrocommunity/completion/cmp-git/README.md
- lua/astrocommunity/completion/cmp-git/init.lua
This adds the [`cmp-git`](https://github.com/petertriho/cmp-git) source for `nvim-cmp` and by default only loads the source for git commits and octo filetypes
> feat(completion): add `cmp-git`

- lua/astrocommunity/recipes/vscode/init.lua
This adds a lot more default mappings to match AstroNvim
> feat(vscode): add more default mappings to vscode integration

- lua/astrocommunity/pack/jj/README.md
- lua/astrocommunity/pack/jj/init.lua
Adds a pack for working with https://github.com/martinvonz/jj
> feat(pack): Add Jujutsu/jj pack

- lua/astrocommunity/pack/typescript/init.lua
This adds support for `conform.nvim` to the Typescript pack in a similar manner to how `null-ls` is checking for `prettier` before enabling it
> feat(typescript): add `conform.nvim` support to typescript pack

- lua/astrocommunity/pack/jj/README.md
- lua/astrocommunity/pack/jj/init.lua
Add [vim-jjdescription](https://github.com/avm99963/vim-jjdescription) to jj pack.
> feat(jj): Add vim-jjdescription to jj pack

- lua/astrocommunity/code-runner/toggletasks-nvim/README.md
- lua/astrocommunity/code-runner/toggletasks-nvim/init.lua
added the toggletasks.nvim plugin
> feat(code-runner): added the toggletasks.nvim plugin

- lua/astrocommunity/terminal-integration/vim-tmux-navigator/README.md
- lua/astrocommunity/terminal-integration/vim-tmux-navigator/init.lua
Add [vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator) in terminal-integration
> feat(terminal-integration): add `vim-tmux-navigator` plugin

- lua/astrocommunity/pack/jj/README.md
- lua/astrocommunity/pack/jj/init.lua
- Adds [lazyjj](https://github.com/Cretezy/lazyjj) (a TUI for jj, similar to lazygit) mapping
Disclamer: I am the author of lazyjj.
> feat(jj): Add lazyjj

- CONTRIBUTING.md
Discord link within CONTRIBUTING.md was a expired temporary link. Now it's a permanent link.
> docs(main): make discord link permanent

- lua/astrocommunity/pack/clojure/README.md
Update pack description after refactor in #982 (sorry it seems this commit got missed from the previous merge, I guess I bungled that too)
Simplify configuration examples to most common approaches.
None
> docs(clojure): update pack description & simplify examples

- lua/astrocommunity/colorscheme/catppuccin/init.lua
> feat(catppuccin): add bufferline integration

- lua/astrocommunity/game/leetcode-nvim/README.md
- lua/astrocommunity/game/leetcode-nvim/init.lua
> feat(game): Add `leetcode.nvim`

- lua/astrocommunity/pack/python/init.lua
Update venv-selector to new regexp branch
added telescope branch 0.1.x and plenary as deps
> feat(python): update venv-selector to new branch

- lua/astrocommunity/pack/python-ruff/init.lua
Change ruff_lsp to ruff
Ruff implements all features of ruff-lsp since [0.4.5](https://github.com/astral-sh/ruff/releases/tag/v0.4.5)
> feat(python-ruff)!: change from ruff_lsp to ruff

- lua/astrocommunity/pack/ocaml/README.md
- lua/astrocommunity/pack/ocaml/init.lua
Added a basic MVP ocaml pack. Revisions mights come.
> feat(pack): Add `ocaml` pack

- lua/astrocommunity/fuzzy-finder/fzf-lua/README.md
- lua/astrocommunity/fuzzy-finder/fzf-lua/init.lua
This adds `fzf-lua` as a fuzzy finder option.
> feat(fuzzy-finder): add `fzf-lua`

- lua/astrocommunity/pack/rust/init.lua
Fix the crates.nvim cmp integration.
> fix(rust): fix crates.nvim cmp integration

- lua/astrocommunity/completion/cmp-calc/README.md
- lua/astrocommunity/completion/cmp-calc/init.lua
Add cmp-calc completion source
> feat(completion): add  cmp-calc

- lua/astrocommunity/completion/cmp-spell/README.md
- lua/astrocommunity/completion/cmp-spell/init.lua
> feat(completion): add cmp-spell

- lua/astrocommunity/editing-support/chatgpt-nvim/init.lua
As in title, very weak opinion about the choice of the key, Cs are taken, I picked `m` as in "modify", also thought of `E` as in "edit"
> fix(chatgpt-nvim): Add missing cmd and bindings

- lua/astrocommunity/editing-support/chatgpt-nvim/init.lua
Reference: https://github.com/jackMort/ChatGPT.nvim#installation
> fix(chatgpt-nvim): add trouble.nvim dependency

- lua/astrocommunity/completion/cmp-tmux/README.md
- lua/astrocommunity/completion/cmp-tmux/init.lua
> feat(completion): add cmp-tmux

- lua/astrocommunity/pack/rust/init.lua
> feat(rust): Add cmp support for crates name

- lua/astrocommunity/lsp/lsp-signature-nvim/init.lua
> fix(lsp-signature-nvim): corrected lazy spec and disable conflicts features from `noice-nvim`

- lua/astrocommunity/completion/codeium-nvim/init.lua
> perf(codeium-nvim): add `event` and `cmd` fields for improved lazy-loading 

- lua/astrocommunity/completion/cmp-nerdfont/README.md
- lua/astrocommunity/completion/cmp-nerdfont/init.lua
> feat(completion): add `cmp-nerdfont`

- lua/astrocommunity/completion/codeium-nvim/init.lua
> feat(codeium-nvim): use `astroui` for the symbols

- lua/astrocommunity/icon/mini-icons/README.md
> docs(mini-icons): Fix typo

- lua/astrocommunity/pack/python-ruff/README.md
- lua/astrocommunity/pack/python/init.lua
> feat(python): Switch `pyright` with `basedpyright`

- lua/astrocommunity/pack/nix/README.md
- lua/astrocommunity/pack/nix/init.lua
R? @luxus 
Partially closes #883
> feat(nix): Replace `nil_ls` with `nixd`

- lua/astrocommunity/completion/codeium-nvim/init.lua
> fix(codeium-nvim): resolve loading issues for nvim-cmp and lspkind.nvim

- lua/astrocommunity/pack/clojure/init.lua
- lua/astrocommunity/pack/dart/init.lua
- lua/astrocommunity/pack/full-dadbod/init.lua
- lua/astrocommunity/pack/haskell/init.lua
- lua/astrocommunity/pack/haxe/init.lua
- lua/astrocommunity/pack/json/init.lua
- lua/astrocommunity/pack/just/init.lua
- lua/astrocommunity/pack/nix/init.lua
- lua/astrocommunity/pack/python/init.lua
- lua/astrocommunity/pack/rust/init.lua
- lua/astrocommunity/pack/scala/init.lua
This is a follow up to #1096 which does a bit of refactor in the packs where it makes sense. It makes sure that each extra plugin a language pack adds for stuff like language tools can be individually disabled without breaking the pack
> refactor(pack): refactor packs to make individual plugins more disablable

- lua/astrocommunity/editing-support/nvim-origami/README.md
- lua/astrocommunity/editing-support/nvim-origami/init.lua
This PR adds https://github.com/chrisgrieser/nvim-origami, yet another plugin by Chris (author of `spider`) aiming to simplify handling of foldable sections.
> feat(editing-support): add `nvim-origami`

- lua/astrocommunity/pack/chezmoi/README.md
- lua/astrocommunity/pack/chezmoi/init.lua
This adds a pack for working with Chezmoi configuration files.
> feat(pack): add Chezmoi pack

- lua/astrocommunity/lsp/nvim-java/README.md
- lua/astrocommunity/lsp/nvim-java/init.lua
Supersedes #1095 . This just adds `nvim-java` as an individual plugin in the LSP category. Seems like a good way to provide it in AstroCommunity for those who want to try it but it's opt-in.
> feat(lsp): add `nvim-java` plugin

- lua/astrocommunity/colorscheme/moonfly/README.md
- lua/astrocommunity/colorscheme/moonfly/init.lua
> feat(colorscheme): Add vim-moonfly-colors

- lua/astrocommunity/pack/laravel/README.md
Closes #1126
Fix the link for blade syntax highlighting to point to the correct thread/comment on how to set it up and fixed them not getting new lined
> fix(pack): update link for blade highlighting

- lua/astrocommunity/media/codesnap-nvim/README.md
- lua/astrocommunity/media/codesnap-nvim/init.lua
> fix(codesnap-nvim): Add default saving path

- lua/astrocommunity/completion/supermaven-nvim/README.md
- lua/astrocommunity/completion/supermaven-nvim/init.lua
Adds configuration for https://github.com/supermaven-inc/supermaven-nvim.
> feat(completion): add supermaven-nvim

- lua/astrocommunity/editing-support/multiple-cursors-nvim/init.lua
> fix(multiple-cursors-nvim)!: Change prefix to `<Leader>m`

- lua/astrocommunity/pack/markdown/init.lua
- lua/astrocommunity/pack/mdx/README.md
- lua/astrocommunity/pack/mdx/init.lua
Closes #1057 
This adds a language pack for MDX
> feat(pack): add `mdx` language pack

- lua/astrocommunity/pack/cs/init.lua
adds `neotest-dotnet` package optionally if "astrocommunity.testing.neotest" pack and "astrocommunity.pack.cs" pack are enabled at the same time testing support for dotnet will be enabled
> feat(cs): add neotest integration with `neotest-dotnet`

- lua/astrocommunity/pack/ocaml/README.md
> docs(ocaml): fix typo

- lua/astrocommunity/git/gitgraph-nvim/README.md
- lua/astrocommunity/git/gitgraph-nvim/init.lua
Adds [`gitgraph.nvim`](https://github.com/isakbm/gitgraph.nvim)
> feat(git): add `gitgraph.nvim`

- lua/astrocommunity/neovim-lua-development/helpview-nvim/README.md
- lua/astrocommunity/neovim-lua-development/helpview-nvim/init.lua
Adds [`helpview.nvim`](https://github.com/OXY2DEV/helpview.nvim)
> feat(neovim-lua-development): add `helpview.nvim`

- lua/astrocommunity/markdown-and-latex/markview-nvim/README.md
- lua/astrocommunity/markdown-and-latex/markview-nvim/init.lua
Adds [`markview.nvim`](https://github.com/OXY2DEV/markview.nvim)
> feat(markdown-and-latex): add `markview.nvim`

- lua/astrocommunity/markdown-and-latex/markview-nvim/init.lua
> fix(markview-nvim): Add missing treesitter parsers

- lua/astrocommunity/neovim-lua-development/helpview-nvim/init.lua
> fix(helpview-nvim): add missing treesitter parser

- lua/astrocommunity/code-runner/molten-nvim/README.md
- lua/astrocommunity/code-runner/molten-nvim/init.lua
> feat(code-runner): Add `molten-nvim`

- lua/astrocommunity/editing-support/copilotchat-nvim/README.md
- lua/astrocommunity/editing-support/copilotchat-nvim/init.lua
Add [CopilotChat.nvim](https://github.com/CopilotC-Nvim/CopilotChat.nvim) with some keybinds
> feat(editing-support): add `CopilotChat.nvim`

- lua/astrocommunity/programming-language-support/rest-nvim/init.lua
[rest.nvim](https://github.com/rest-nvim/rest.nvim) got updated. This updates the plugin to use the new configuration
> fix(rest-nvim): update to v3

- lua/astrocommunity/split-and-window/neominimap-nvim/README.md
- lua/astrocommunity/split-and-window/neominimap-nvim/init.lua
This adds the [`neominimap.nvim`](https://github.com/Isrothy/neominimap.nvim) plugin
> feat(split-and-window): add `neominimap.nvim`

- lua/astrocommunity/pack/python/README.md
fix(python): Updated info about language server used in pack
> docs(python): Swap mentions of `pyright` with `basedpyright`

- lua/astrocommunity/bars-and-lines/bufferline-nvim/init.lua
Added a missing binding to toggle pin buffer.
> feat(bufferline-nvim): add buffer toggle pin binding

- lua/astrocommunity/markdown-and-latex/markdown-preview-nvim/init.lua
Add useful mappings to `mardown-preview-nvim`.
> feat(markdown-preview-nvim): add keybindings

- lua/astrocommunity/media/img-clip-nvim/README.md
- lua/astrocommunity/media/img-clip-nvim/init.lua
> feat(media): add `img-clip.nvim`

- lua/astrocommunity/markdown-and-latex/render-markdown-nvim/README.md
- lua/astrocommunity/markdown-and-latex/render-markdown-nvim/init.lua
> feat(markdown-and-latex): add `render-markdown.nvim`

- lua/astrocommunity/colorscheme/everblush-nvim/README.md
- lua/astrocommunity/colorscheme/everblush-nvim/init.lua
Adds the everblush colorscheme.
> feat(colorscheme): Add Everblush

- lua/astrocommunity/colorscheme/horizon-nvim/README.md
- lua/astrocommunity/colorscheme/horizon-nvim/init.lua
Add the horizon colorscheme from https://github.com/LunarVim/horizon.nvim
> feat(colorscheme): Add Horizon

- lua/astrocommunity/media/neocord-nvim/init.lua
> fix(neocord-nvim): fix typo

- lua/astrocommunity/code-runner/executor-nvim/README.md
Adds missing readme for `google/executor.nvim`.
> docs(executor-nvim): add missing readme for executor.nvim

- lua/astrocommunity/completion/cmp-tmux/README.md
Wrong title in cmp-tmux README.md
> docs(cmp-tmux): Fix wrong title in cmp-tmux readme

- lua/astrocommunity/pack/moonbit/init.lua
This change is made because @tonyfettes has transferred the plugin's ownership to `moonbit-community`[^1], and the old address now points to a personal fork, which can get out of sync.
[^1]: As a verification, the PR @mehalter once made to the plugin has been moved to https://github.com/moonbit-community/moonbit.nvim/pull/3.
> feat(pack): use `moonbit.nvim` from `moonbit-community`

- lua/astrocommunity/utility/nvim-toggler/README.md
Removes repeated fragment of text in README.md
> docs(nvim-toggler): remove repetition in README

- lua/astrocommunity/colorscheme/palenight-nvim/README.md
- lua/astrocommunity/colorscheme/palenight-nvim/init.lua
Add palenight.nvim colorscheme
I chose https://github.com/wilmanbarrios/palenight.nvim over https://github.com/drewtempelmeyer/palenight.vim because it has great support for LSP/Treesitter/etc.
> feat(colorscheme): add palenight.nvim colorscheme

- lua/astrocommunity/project/linear-nvim/README.md
- lua/astrocommunity/project/linear-nvim/init.lua
Unsure about the deps.
They seem to be required. 
Added in keymaps that will conflict with overseer.
> feat(project): Add in linear-nvim

- lua/astrocommunity/colorscheme/github-nvim-theme/README.md
Update the README documentation for the `github-nvim-theme` community plugin.
> docs(github-nvim-theme): update README.md

- lua/astrocommunity/session/vim-workspace/README.md
- lua/astrocommunity/session/vim-workspace/init.lua
Add vim-workspace plugin and session directory.
If a new `session` directory is not ok... I guess `workflow` or `project` dir? I wasn't able to decide, please guide me.
> feat(session): add vim-workspace plugin and session directory

- lua/astrocommunity/project/linear-nvim/init.lua
This makes more sense semantically
> fix(linear-nvim)!: Change leader from `<Leader>m` to `<Leader>L`

- lua/astrocommunity/pack/tailwindcss/init.lua
Closes #1328 
This should add support for new TailwindCSS v4, which removed config based approach.
> fix(tailwindcss): resolve root dir based on installed dependency

- lua/astrocommunity/colorscheme/gruvbox-nvim/README.md
- lua/astrocommunity/editing-support/chatgpt-nvim/README.md
- lua/astrocommunity/editing-support/copilotchat-nvim/README.md
- lua/astrocommunity/media/pets-nvim/README.md
- lua/astrocommunity/pack/hyprlang/README.md
- lua/astrocommunity/pack/laravel/README.md
- lua/astrocommunity/utility/telescope-fzy-native-nvim/README.md
> docs: Make sure links are fenced

- lua/astrocommunity/pack/go/init.lua
Gopls 18 got released 3 days ago. 
Closes #1307
> fix(go): Remove deleted lsp option

- lua/astrocommunity/fuzzy-finder/fzf-lua/init.lua
https://github.com/ibhagwan/fzf-lua/commit/7cede182cf7463376669e102bd10d13f8ce05e52
> feat(fuzzy-finder): use jump1 as jump_to_single_result is deprecated

- lua/astrocommunity/completion/blink-cmp/init.lua
Enables catppuccin blink.cmp integration.
> feat(blink-cmp): enable catppuccin blink.cmp integration

- lua/astrocommunity/editing-support/copilotchat-nvim/init.lua
Due to deprecation, this is the new recommended way of selecting a prompt action. As a side note, I think this fixes an issue with the snacks picker not working at the moment.
See for more information: 
- https://github.com/LazyVim/LazyVim/pull/5707
- https://github.com/CopilotC-Nvim/CopilotChat.nvim/blob/630a74739e946390ffb183682a86ec370a5ae294/lua/CopilotChat/actions.lua#L12
> fix(copilotchat-nvim): use built-in prompt actions select

- lua/astrocommunity/pack/typescript/README.md
This makes the code block properly formatted, which caused the issue for the generated docs website, even though it renders fine in GitHub.
> docs(typescript): add missing closing code block quotes

- lua/astrocommunity/motion/mini-jump/README.md
- lua/astrocommunity/motion/mini-jump/init.lua
Add [Mini.Jump](https://github.com/echasnovski/mini.jump) plugin
> feat(motion): add mini-jump plugin

- README.md
This adds some additional information about being able to override aspects of an imported pack.
> docs(main): clarify posibility of overriding aspects of a pack

- lua/astrocommunity/ai/kurama622-llm-nvim/README.md
Fixes the GitHub repository URL.
> docs(kurama622-llm-nvim): fix repo url

- lua/astrocommunity/editing-support/neogen/init.lua
This adds three additional languages to Neogen: `javascript`, `javascriptreact` and `ruby`.
> feat(neogen): Add additional languages to Neogen

- .github/workflows/ci.yml
- .github/workflows/pages.yml
I understand that contributors are supposed to make different branch other than main,
but I think it's safe to assume, a lot of people forget it or just don't care
It's just a suggestion, hope you accept those changes
> ci: trigger actions only in original repository

- lua/astrocommunity/completion/avante-nvim/init.lua
- adding custom vendors to the copilot provider
> feat(avante-nvim): adding avante as a blink source

- .gitignore
- flake.lock
- flake.nix
Might be useful for our nix users
> build: add in nix devShell, and ignore direnv

- lua/astrocommunity/completion/blink-cmp-git/README.md
- lua/astrocommunity/completion/blink-cmp-git/init.lua
Add blink-cmp-git this time.
I did the same form as the previous one.
Moving to blink.
> feat(completion): add blink-cmp-git

- lua/astrocommunity/completion/nvim-cmp/init.lua
Fixes https://github.com/AstroNvim/astrocommunity/issues/1414
> fix(nvim-cmp): misspelled `mapping` variable

- lua/astrocommunity/editing-support/vim-exchange/README.md
- lua/astrocommunity/editing-support/vim-exchange/init.lua
[`vim-exchange`](https://github.com/tommcdo/vim-exchange) provides the ability to exchange text and visual selections
> feat(editing-support): add vim-exchange plugin

- lua/astrocommunity/recipes/vscode/init.lua
Adds [nvim-surround](https://github.com/kylechui/nvim-surround) to the list of supported plugins of `recipes/vscode`
Thanks!
> feat(vscode): add nvim-surround to supported plugins list

- lua/astrocommunity/programming-language-support/kulala-nvim/README.md
- lua/astrocommunity/programming-language-support/kulala-nvim/init.lua
> feat(programming-language-support): add kulala.nvim

- lua/astrocommunity/completion/minuet-ai-nvim/README.md
- lua/astrocommunity/completion/minuet-ai-nvim/init.lua
Closes #1341 
Minimal config, should be improved down the road by the community.
> feat(completion): Add minimal minuet-ai

- lua/astrocommunity/note-taking/obsidian-nvim/README.md
- lua/astrocommunity/note-taking/obsidian-nvim/init.lua
Switch to `obsidian-nvim/obsidian.nvim` and add `blink` to plugin pickers
> fix(obsidian-nvim): Change remote to up to date fork, blink.cmp integration and add in daily-notes folder

- lua/astrocommunity/completion/blink-cmp-git/init.lua
https://github.com/Kaiser-Yang/blink-cmp-git/commit/2d9f19078c452988f13834d9ef207acfa37f1eaf
> fix(blink-cmp-git): Remove unneeded dependency

- lua/astrocommunity/pack/sql/init.lua
> fix(sql): Dont overide opts.handlers table

- lua/astrocommunity/pack/java/init.lua
Added missing root markers.
https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs/jdtls.lua#L90
Is there some way to reference the default root markers from lspconfig? Would be good to avoid duplication.
> fix(java): update root markers

- lua/astrocommunity/lsp/sonarlint-nvim/init.lua
Copied optional by mistake from my config.
> fix(sonarlint-nvim): remove optional

- lua/astrocommunity/pack/oxlint/README.md
- lua/astrocommunity/pack/oxlint/init.lua
> feat(pack): add oxlint pack

- lua/astrocommunity/programming-language-support/kulala-nvim/init.lua
This resolves all of the bugs introduced by https://github.com/AstroNvim/astrocommunity/pull/1551 and https://github.com/AstroNvim/astrocommunity/pull/1539
> fix(kulala-nvim): resolve bugs in keymap setup and breaking lazy loading in general

- lua/astrocommunity/editing-support/mcphub-nvim/init.lua
Remove custom options and use the defaults provided by the plugin: https://ravitemer.github.io/mcphub.nvim/configuration.html
> feat(mcphub-nvim)!: Dont override opts 

- lua/astrocommunity/pack/nushell/README.md
- lua/astrocommunity/pack/nushell/init.lua
Closes #1594 
Adds the nushell language pack
Wasn't 100% sure if conform installs it's own `nufmt`, but I was pretty sure it doesn't - so I put it in the readme as needing a local install.
> feat(pack): add nushell language pack

- lua/astrocommunity/pack/purescript/init.lua
> fix(purescript): update nvimmer-ps url

- lua/astrocommunity/ai/opencode-nvim/README.md
- lua/astrocommunity/ai/opencode-nvim/init.lua
Add [opencode.nvim](https://github.com/NickvanDyke/opencode.nvim)
The binding are the default one shown in the repo
> feat(ai): add `NickvanDyke/opencode.nvim`
