AstroNvim/astrocommunity

lua/astrocommunity/pack/go/go.lua
lua/astrocommunity/pack/rust/rust.lua
lua/astrocommunity/pack/typescript/typescript.lua

This lets users simply add language packs rather than needing to have to remember to go update their `lsp.setup_handlers` table.

feat(pack): make language packs work without user intervention

---

lua/astrocommunity/motion/mini-ai/mini-ai.lua

The mini-ai astrocommunity plug-in was not working because the setup function was not being called.  According to lazy docs, it seems to imply that it should automatically call setup, but this plug-in did not work without explicitly defining our own config that calls setup.

fix(mini-ai): explicitly call setup()

---

lua/astrocommunity/pack/java/README.md
lua/astrocommunity/pack/java/java.lua

Closes #75
Hi There,
Spent a part of the week making the java pack. The commit tree is really messy as I was using a git reference to the package to test it (probs not the best idea).
The package adds quite a few things so I'll list them here
- Adds `java` treesitter parsers
- Adds `html` treesitter parsers (XML)
- Adds `jdtls` language server
- Adds `lemminx` language server (XML)
- Adds [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls) for language specific tooling
- Adds `clang_format` through null-ls
- Adds `javadbg` and `javatest` debug adapters for nvim-dap

feat(pack/java): add Java Language Pack

---

lua/astrocommunity/pack/tailwindcss/tailwindcss.lua

AstroNvim's default config disables color highlighting for names, which prevents tailwind color highlighting from working properly

fix(pack): enable tailwindcss color highlighting

---

lua/astrocommunity/pack/toml/toml.lua

Relies on https://github.com/AstroNvim/AstroNvim/pull/1695 and release of AstroNvim v3.5.3 (@sjcobb2022)

fix(pack): disable taplo in null-ls

---

lua/astrocommunity/pack/java/java.lua

- found this fix from https://github.com/hrsh7th/nvim-cmp/issues/1017
- this fix is working fine in my local

fix(pack): improve compatibility of table.unpack function

---

lua/astrocommunity/pack/rust/README.md
lua/astrocommunity/pack/rust/rust.lua

Sets up rust-tools to debug with codelldb from Mason instead of lldb-vscode from the system.
Closes #84.

feat(pack): switch to codelldb for rust debugging

---

lua/astrocommunity/markdown-and-latex/vimtex/README.md
lua/astrocommunity/markdown-and-latex/vimtex/vimtex.lua

disabling `lazy` by default makes it load when editing a .tex file

feat(markdown-and-latex): add vimtex

---

CONTRIBUTING.md

The url was previously defined without a scheme so Github tried to navigate a user to a non-existing file in this repo instead of the website.

chore: fix url to NeovimCraft

---

lua/astrocommunity/pack/rust/rust.lua

In the `init` function we are setting up a autocommand that loads this plugin and sets up `cmp`. We don't need this other event in the lazy definition.

chore(pack): remove unnecessary event from rust pack

---

lua/astrocommunity/completion/copilot-lua-cmp/copilot-lua-cmp.lua

- Re-enable C-e to turn off cmp window to see overlapping hidden copilot suggestion without losing said suggestion
- Add C-x and C-z mappings to go to next and previous copilot suggestions
This suggestion comes from an issue I have been having where whenever copilot gives a multi-line suggestion the overlapping cmp window hides it. By re-enabling C-e we can quickly shutoff the window without losing the suggestion and then we can go through them using the new mappings I added.

feat(completion): improve copilot-cmp defaults 

---

lua/astrocommunity/note-taking/neorg/neorg.lua

Neorg has a new configuration change removing the ".nerog" in many of it's modules.

fix(note-taking): use new neorg v3 config options

---

lua/astrocommunity/pack/json/README.md
lua/astrocommunity/pack/json/json.lua

It seems counterintuitive to have `jsonls` and `prettierd` fight for formatting. 
I encountered several instances where prettierd won the formatting over jsonls and vice versa. 
I am uncertain if it's connected to that, but might as well be: Running into timeouts and/or freezing up neovim until one formatter wrote its changes..

fix: Don't pull in prettierd

---

lua/astrocommunity/editing-support/nvim-ts-rainbow2/nvim-ts-rainbow2.lua

Recently, I've noticed that my editor slows down over time. Turns out that this hack is causing the problem. Without it, there is no more slowdown.

fix(nvim-ts-rainbow2): remove hack

---

lua/astrocommunity/git/octo/octo.lua

Sorry, this got lost somehow along the way. This was discussed in #138 as a better fit than `<leader>G` until a better integration has been found

fix: readd <leader>O as a prefix for octo

---

lua/astrocommunity/pack/python/README.md
lua/astrocommunity/pack/python/python.lua

Pylint is a very popular linter, unfortunately it doesn't work out of the box if you are using a virtualenv (as you should be doing). This issue in mason.nvim describes why it doesn't work and how to apply a workaround: https://github.com/williamboman/mason.nvim/issues/668

feat: Add Pylint and make it work in a virtualenv

---

lua/astrocommunity/pack/rust/rust.lua

Currently, if you are on Windows and you try to use the rust debugger you will get errors and you won't be able to use the debugger. #167 
In this PR I fix that issue by correcting the path when the plugin is run on windows.

fix(pack): make codelldb point to the right path in windows

---

lua/astrocommunity/pack/typescript-all-in-one/README.md
lua/astrocommunity/pack/typescript-all-in-one/typescript.lua
lua/astrocommunity/pack/typescript-deno/README.md
lua/astrocommunity/pack/typescript-deno/typescript.lua
lua/astrocommunity/pack/typescript/README.md
lua/astrocommunity/pack/typescript/typescript.lua

As described [here](https://github.com/AstroNvim/astrocommunity/issues/120) I am looking to add separate packs for both tsserver, denols & tsserver + denols for TypeScript developers. This is a first attempt at doing it and the changes are yet to be tested. The reason why I already open a PR is so the original authors of the typescript pack can take a look at it and possibly extend the functionality (especially to the denols pack) to create a more mature prduct.
Personally I'd also consider adding `eslint_d` to the tsserver pack, please let me know your opinions about that.
Resolves #120

feat(pack): create multiple typescript packs

---

lua/astrocommunity/completion/copilot-lua-cmp/copilot-lua-cmp.lua

It is very useful to accept Co-pilot suggestions one word at a time or even a whole line.  Copilot offers these features but they have not been exposed.  VS Code, by default uses Ctrl+Right to accept a word.  I've added similar vim-like controls:
* Ctrl+Right/L for accepting a word
* Ctrl+Down/J for accepting a line
* Ctrl+C to dismiss the suggestion

feat(completion): added more mappings for copilot-lua-cmp

---

lua/astrocommunity/pack/typescript/typescript.lua

This allows neo-tree to be disabled by overrriding the config and allow the plugin to keep working.

refactor(pack): require neo-tree later in typescript

---

lua/astrocommunity/pack/tailwindcss/README.md
lua/astrocommunity/pack/tailwindcss/tailwindcss.lua

The previous plugin uses hardcoded values when determining which colors to display in the completion menu, which creates inconsistencies when custom tailwind colors are defined.

feat(pack): show custom tailwindcss colors in cmp menu

---

lua/astrocommunity/pack/rust/rust.lua

We have this issue on NixOS but potentiall also other operating systems such as *BSDs and non-mainstream cpu architectures are affected by this.

fix(pack): gracefully rust plugin if codelldb is not available

---

lua/astrocommunity/pack/java/java.lua

Since the introduction of the new registry, packages started linking
more than executables (`bin/`) in Mason's root directory. Examples of
these are platform-agnostic "share" files, for example the JARs used
here.
Reaching into the internal package structures of Mason packages is not
stable and is prone to break across versions.

fix(java): use stable file locations for JARs provided by mason.nvim

---

lua/astrocommunity/pack/clojure/README.md
lua/astrocommunity/pack/clojure/clojure.lua

Add a clojure pack to the Astrocommunity
- Treesitter parser: clojure
- LSP: clojure_lsp
- Plugins: "Olical/conjure" and "gpanders/nvim-parinfer"
- Add autocmd to disable lsp diagnostics in Conjure log
- Add autocmd to configure comments to Clojure style guide
Add a localleader mapping to the user config (if not defined in AstroNvim) to enable Conjure key mappings, e.g. `, e r` to evaluate top level root
Define a localleader mapping in `options.lua`
```lua
return {
g = {
mapleader = " ",                 -- sets vim.g.mapleader
maplocalleader = ",",            -- Set local leader key binding
-- additional options...
},
}
```
An autocmd is used to set ;; as the line comment character, to follow the Clojure style guide.
Resolve #247

feat(pack): clojure language pack

---

README.md

The `README` should reflect the new colorscheme names.

chore: update readme according to breaking renames

---

lua/astrocommunity/pack/angular/README.md
lua/astrocommunity/pack/angular/angular.lua

Hello,
I noticed there wasn't any pack for Angular so I made one for myself.
Maybe it is useful to someone else.

feat(pack): adds angular pack

---

lua/astrocommunity/pack/lua/lua.lua

Since `selene` got removed from lua pack in 4caa6da and pretty much every plugin developer using `luacheck`, I think it would be a good idea to add it as linter, especially because Astronvim uses it and `.luacheckrc` is already configured there, so it's not going to be a wall of warnings like `accessing undefined variable 'vim'`

feat(pack): add luacheck linter to lua pack

---

lua/astrocommunity/pack/typescript/typescript.lua

This seems like a pretty good way to improve the `prettier` and `eslint` loading. This does make it so that `eslint` is preferred over `prettier` if there are no configuration files for both specifically. This could be changed/improved based on suggestions probably from someone who works with these language servers/linters/formatters more than I do
Resolves #225

fix(typescript): improve eslint and prettier loading

---

lua/astrocommunity/pack/typescript/typescript.lua

- Removed `or not has_prettier` from null_ls eslint_d diagnostics registration. Eslint should only be registered if `has_eslint` returns true. It should not be registered just because a project does not have a  prettier config.
- Added `null_ls.builtins.formatting.eslint_d`
- Added `null_ls.builtins.code_actions.eslint_d`
- Fixed `prettier.config.(c)js` filenames

fix(typescript): fix null_ls eslint_d registration(s)

---

lua/astrocommunity/motion/flit-nvim/README.md
lua/astrocommunity/motion/flit-nvim/flit-nvim.lua
lua/astrocommunity/motion/leap-nvim/README.md
lua/astrocommunity/motion/leap-nvim/leap-nvim.lua

This change has the benefit that only one of those plugins is active instead of both reserving keybinds

feat(motion)!: separate flit.nvim from leap.nvim

---

lua/astrocommunity/pack/python/README.md

in 88adb54ebda4ee85842198eb06c5b1ed5585cb79

docs(pack): fix python pack README, as pylint was removed

---

lua/astrocommunity/color/ccc-nvim/ccc-nvim.lua

Fix attached buffer error and utilize the auto loading instead of calling it directly since we're passing in the auto_enable option. https://github.com/uga-rosa/ccc.nvim/commit/5a9e394e61925d71f9c1c0cd1fd30ce463d8be46
Did nothing to affect code style so not sure why the action is failing...

fix(ccc-nvim.lua): highlighter attached buffer error

---

lua/astrocommunity/motion/leap-nvim/leap-nvim.lua

explicitly bind default mappings using 'key' for more intuitive overriding.

chore(motion): add missing desc to leap binds

---

lua/astrocommunity/pack/tailwindcss/README.md
lua/astrocommunity/pack/tailwindcss/tailwindcss.lua

Rustywind sorts Tailwind class names, however it doesn't follow the official [Tailwind Prettier plugin](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier). Only one should be included

fix: Remove rustywind from tailwindcss pack

---

lua/astrocommunity/pack/tailwindcss/tailwindcss.lua

This resolves the issue where the kind "Color" would be displayed instead of its corresponding icon in the cmp menu when a tailwindcss color does not exist for a given entry.

fix(pack/tailwindcss): use icon when color is not available for cmp

---

lua/astrocommunity/motion/harpoon/init.lua

I believe it's better when you have to remember one less keybinding.
Hope nobody gets upset because of the removed "j" keymap.
I may add it for compatibility

feat(harpoon)!: remove "j" keymap, make "t" keymap dynamic based on $TMUX

---

lua/astrocommunity/motion/harpoon/init.lua

Hello, after the changes in #292 it started to fail with:
``` attempt to concatenate local 'running_tmux_session' (a boolean value)```
This PR should fix the issue.

fix(harpoon): typo in concatenation

---

lua/astrocommunity/pack/typescript/init.lua

According to [this](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1552) null-ls issue, [Astro.build](https://astro.build/) filetypes needs to be added as `extra_filetypes`.
I thought it made sense to add it in the typescript pack since you'll be writing js/ts with Astro anyway.
The `astro-language-server` uses Prettier [under the hood](https://github.com/withastro/language-tools/tree/main/packages/language-server) so it doesn't have to be added to the `prettierd` handler.

feat: add astro filetype to eslint_d handler in typescript pack

---

lua/astrocommunity/pack/clojure/init.lua

Add comment between `;;` comment characters for clojure and text being commented

fix(clojure): add space after clojure comment character

---

lua/astrocommunity/editing-support/ultimate-autopair-nvim/README.md
lua/astrocommunity/editing-support/ultimate-autopair-nvim/init.lua

Update suggested fly-mode config and maintain notification behavior from nvim-autopairs

fix(ultimate-autopair-nvim): update ultimate-autopair.nvim

---

lua/astrocommunity/motion/flash-nvim/README.md
lua/astrocommunity/motion/flash-nvim/init.lua

feat(motion): add move plugin flash nvim

---

lua/astrocommunity/pack/ruby/README.md

The [Ruby pack](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/ruby/init.lua) does not install `html` or `ruby_ls`.

docs(ruby): Remove mentions of html and ruby_ls from docs.

---

lua/astrocommunity/pack/python/init.lua

Mason installs debugpy in a venv in $HOME/.local/share/$NVIM_APPNAME/mason/packages/debugpy/ .
This fixes a bug where DAP would not find debugpy (ModuleNotFoundError : no module named "debugpy") and would not start debugging.
The replaced code would only work if you just installed debugpy or running :DapInstall python and use DAP without exiting nvim, or if you had debugpy installed system-wide (via pip) and not using a venv. It would fail upon new nvim runs.

fix(python): added debugpy path auto-resolution using mason-registry

---

lua/astrocommunity/motion/harpoon/init.lua

I believe the Harpoon entry in which-key should be blue because it is a nested keymap,  unfortunately when using `keys` it doesn't get highlighted properly, this pr fixes it.
**Before:**
**After:**

fix(harpoon): Make which-key entry color blue, as it should be

---

lua/astrocommunity/debugging/telescope-dap-nvim/README.md
lua/astrocommunity/debugging/telescope-dap-nvim/init.lua

This plugin is also overriding dap internal ui, so running any dap command, which makes use of the internal ui, will result in a telescope prompt.

feat(debugging): add telescope dap extension

---

lua/astrocommunity/note-taking/obsidian-nvim/README.md
lua/astrocommunity/note-taking/obsidian-nvim/init.lua

As requested from #309. We need this config to follow links to other markdown files. Please check if anything is amiss. 
Edit: I see the review checklist asks for "Proper usage of `opts` table rather than setting things up with the `config` function." I'm not sure if that is satisfied here.

fix(obsidian-nvim): added obsidian.nvim config and changed the readme

---

lua/astrocommunity/debugging/nvim-dap-virtual-text/README.md
lua/astrocommunity/debugging/nvim-dap-virtual-text/init.lua

This plugin adds virtual text support to `nvim-dap`. `nvim-treesitter` is used to find variable definitions.

feat(debugging): add nvim-dap-virtual-text

---

lua/astrocommunity/markdown-and-latex/vimtex/init.lua

<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

feat(vimtex): add which-key mapping descriptions

---

lua/astrocommunity/motion/leap-nvim/init.lua

https://github.com/ggandor/leap.nvim/issues/70

fix(leap-nvim): duplicate cursor when leaping

---

lua/astrocommunity/search/nvim-hlslens/init.lua

Adds a lazy event to hlslens, since plugin is not loaded when searching buffer.

fix(nvim-hlslens): add lazy event

---

lua/astrocommunity/diagnostics/lsp_lines-nvim/init.lua

I wish I could have implemented the fix and the keybinds better.
`virtual_text` should be off when using `lsp_lines.nvim`

feat(lsp_lines-nvim): disable virtual text and add `<leader>uD` mapping

---

lua/astrocommunity/project/nvim-spectre/init.lua

I believe the Spectre entry in which-key should be blue because it is a nested keymap, unfortunately when using keys it doesn't get highlighted properly, this pr fixes it.

fix(nvim-spectre): Make which-key entry color blue

---

lua/astrocommunity/motion/grapple-nvim/init.lua

**Before**:
**After**:
Definitely not opinionated or anything :)

feat(grapple-nvim): change grapple icon from arrow to hook to distinguish from harpoon

---

lua/astrocommunity/git/octo-nvim/init.lua

Yet another one of like #376 and what after it. Also, remove default `mappings` which the plugin sets, to avoid keymap mess

fix(octo-nvim): which-key description and color for nested entries

---

README.md

As ts-rainbow2 is deprecated in favor of rainbow-delimiters, this should also be reflected within our catppuccin integration example

docs(catppuccin): replace ts-rainbow2 integration for catppuccin example

---

lua/astrocommunity/test/neotest/init.lua

I’d let mehalter double check this one
Closes #406

fix(neotest): Fix bug in neotest by checking for existing library key table 

---

lua/astrocommunity/editing-support/zen-mode-nvim/init.lua

Previously, the winbar would enable itself on various events (switching buffers, writing to file, which-key popups, telescope, etc.) I added an autocmd that will disable the winbar for all these events while ZenMode is enabled. This does feel a bit hacky though, so please let me know if there's a better way to toggle the winbar.
Additionally, this fixes an issue where previous mini.indentscope options would not be restored upon exiting ZenMode.

fix(zen-mode-nvim): ensure winbar stays disabled and restore old mini.indentscope options

---

lua/astrocommunity/colorscheme/catppuccin/init.lua

We use alpha.nvim for the start screen, might as well enable it.
Also sorting integrations alphabetically makes adding/removing later nicer.

fix(catppuccin): enable alpha.nvim by default

---

lua/astrocommunity/editing-support/chatgpt-nvim/init.lua

fix(chatgpt-nvim): typo in `dependencies` key

---

lua/astrocommunity/lsp/lsp-signature-nvim/README.md
lua/astrocommunity/lsp/lsp-signature-nvim/init.lua

feat(lsp): add ray-x/lsp_signature.nvim

---

lua/astrocommunity/editing-support/zen-mode-nvim/README.md
lua/astrocommunity/editing-support/zen-mode-nvim/init.lua

This fixes an assortment of weird visual bugs when using vim-matchup in zen-mode:
**Before:**
**After:**

feat(zen-mode-nvim): add integration with vim-matchup if enabled

---

lua/astrocommunity/colorscheme/nord-nvim/README.md

Without the proposed change code looks like this:
With the proposed change it looks like this:

chore(nord-nvim): update colorscheme readme

---

lua/astrocommunity/git/neogit/README.md

Add neogit config override in readme showing how to check if noice-nvim is avaialble rather than the default nvim-notify
Note: if there is a way to make a check for either nvim-notify or noice-nvim then that would be more useful

docs(neogit): add noice notification check in readme

---

lua/astrocommunity/pack/go/init.lua

Go modules, module checksum, and workspaces should have syntax highlighting.

fix(go): Add extra treesitter languages for Go

---

lua/astrocommunity/pack/helm/README.md
lua/astrocommunity/pack/helm/init.lua

Setting up treesitter, language server and vim-helm.

feat(pack): Adding helm pack

---

lua/astrocommunity/completion/copilot-lua-cmp/init.lua

Since cycling through basic `cmp.nvim` completions with `<C-j>,<C-k>` is a common usage, it feels more natural to map the copilot accept line action to one of the alternative (`<C-n>,<C-p>`) keymappings of `cmp.nvim`. Also since cycling with `<Tab>` is not possible if there is a copilot suggestion it becomes a bit inconvenient with the current mapping.

chore(copilot-lua-cmp): alter accept line key mapping

---

lua/astrocommunity/pack/java/README.md
lua/astrocommunity/pack/java/init.lua

Users can now see when nvim-jdtls is ready

feat(pack): enable hot reloading in java and show java lsp progress

---

lua/astrocommunity/bars-and-lines/bufferline-nvim/init.lua

Since `Neo-tree` is the default file explorer, it would be nice to add the `neo-tree` offset to `bufferline` by default as:
Currently it looks like this:

chore(bufferline-nvim): add neo-tree offset

---

lua/astrocommunity/editing-support/auto-save-nvim/init.lua

Formatting on save with the automatic saving breaks undo because whenever you undo it reformats immediatley. This disables the automatic formatting when buffers are auto saved. It still lets auto formatting work when saving manually with `:w` for example.

fix(auto-save-nvim): disable format on save when auto saving

---

lua/astrocommunity/pack/ansible/init.lua

`vim.filetype.getlines` is actually a private function (I did this originally so my b 😢). This moves it to the correct public API

fix(ansible): use public API for getting buffer lines

---

lua/astrocommunity/pack/rust/init.lua

Lazy load `crates.nvim` when Cargo.toml is loaded

fix(rust): Lazy load crates.nvim on BufRead Cargo.toml event

---

lua/astrocommunity/pack/typescript/init.lua

```
lazy: require("lazy.health").check()
lazy.nvim
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found
- WARNING {package-info.nvim}: unknown key <requires>
```
Based on [this example in AstroNvim](https://github.com/AstroNvim/AstroNvim/blob/26aedacec6a3d2aeba44c365360b3ba3637b20ca/lua/plugins/neo-tree.lua#L4), this appears to be the right syntax.

fix(typescript): Requires should be dependencies

---

lua/astrocommunity/bars-and-lines/bufferline-nvim/init.lua

I noted that the neo-tree offset was not applied after switching to bufferline.nvim from astrocommunity. Seems that I missed the `options` struct when copy paste from my local bufferline config in this PR https://github.com/AstroNvim/astrocommunity/pull/510 😅

fix(bufferline-nvim): fix neo-tree offset

---

lua/astrocommunity/git/openingh-nvim/init.lua

Use keys and cmd for lazy loading openingph-nvim instead of event
I made the description of the keys generic on purpose because the plugin author states that it supports not only Github but also other git hosting sites. Also, this plugin has a nice notification message if you try to use it not inside a git repository so I don't see a problem with using cmd and keys

fix(openingh-nvim): more precise lazy loading with "cmd" and "keys"

---

lua/astrocommunity/git/blame-nvim/README.md
lua/astrocommunity/git/blame-nvim/init.lua

Adds [blame.nvim](https://github.com/FabijanZulj/blame.nvim), a fugitive style git blame visualizer:

feat(git): add blame.nvim

---

lua/astrocommunity/workflow/hardtime-nvim/init.lua

This disables `hardtime-nvim` on `neo-tree-popup` filetypes. This allows usage of arrow keys when the pop up for file/dir creation, deletion, and renaming shows up.
Closes #530

fix(hardtime-nvim): disable hardtime-nvim on neo-tree-popup

---

lua/astrocommunity/bars-and-lines/dropbar-nvim/init.lua

Load `dropbar.nvim` after `UIEnter` cause visual flicking during startup.

fix(dropbar-nvim): Fix visual flicking bug caused by loading event trigger

---

lua/astrocommunity/completion/cmp-cmdline/init.lua

Lazy load `cmp-cmdline`, for faster startup time.
Original implementation load `cmp` at startup.

perf(cmp-cmdline): lazy load

---

lua/astrocommunity/note-taking/obsidian-nvim/README.md
lua/astrocommunity/note-taking/obsidian-nvim/init.lua

Remove annoying notification
according to the plugin's `help`:
If you want the `gf` passthrough functionality but you’ve already overridden
the `gf` keybinding, just change your `gf` mapping definition to something like
this:
```lua
vim.keymap.set("n", "gf", function()
if require("obsidian").util.cursor_on_markdown_link() then
return "<cmd>ObsidianFollowLink<CR>"
else
return "gf"
end
end, { noremap = false, expr = true })
```
Then make sure to comment out the `gf` keybinding in your obsidian.nvim config:
```lua
mappings = {
-- ["gf"] = require("obsidian.mapping").gf_passthrough(),
},
```

fix(obsidian-nvim): remove annoying notification about "gf" mapping

---

lua/astrocommunity/editing-support/nvim-devdocs/README.md
lua/astrocommunity/editing-support/nvim-devdocs/init.lua

This PR adds the [nvim-devdoc](https://github.com/luckasRanarison/nvim-devdocs) plugin
<details>
<summary>Without glow</summary>
</details>
<details>
<summary>WIth glow</summary>
</details

feat(editing-support): added nvim-devdocs plugin

---

lua/astrocommunity/indent/mini-indentscope/init.lua

Prevents indentscope from loading on special buftypes ("nofiles", "terminal", "quickfix", "prompt"), similar to indent blankline
None

fix(mini-indentscope): exclude special buftypes

---

lua/astrocommunity/editing-support/yanky-nvim/init.lua

there can not set event 'User AstroFile', because restore session from resession.nvim will not tigger 'User AstroFile' event.

fix(yanky-nvim): Fix yanky.nvim loading when restoring session

---

lua/astrocommunity/editing-support/zen-mode-nvim/init.lua

Fixes an issue where toggling a floating terminal will enable the winbar again. Also removes the unecessary "BufWritePost" autocmd event.
None

fix(zen-mode-nvim): disable global winbar upon entering zen mode

---

CHANGELOG.md
lua/astrocommunity/pack/python/README.md
lua/astrocommunity/pack/python/init.lua

It's a common way to sort Python imports on save. `ruff_lsp` could be used to sort the imports the exact same way through code actions, but I'm not sure how to do that on file save.

fix(python): Adds Imports Sorting with isort to the Python Pack

---

lua/astrocommunity/motion/vim-matchup/init.lua

This will leave the option set to 0 by default
See demo video of the issue on https://github.com/AstroNvim/AstroNvim/issues/2276

fix(vim-matchup): remove matchup_match_paren_deferred option

---

lua/astrocommunity/pack/haskell/init.lua

- Since version `2.1.0`, haskell-tools.nvim automatically discovers DAP launch configurations if both `nvim-dap` and `haskell-debug-adapter` are installed.
- See https://github.com/AstroNvim/astrocommunity/pull/553#issuecomment-1707147579
@Uzaaft @Per48edjes 
The `2.1.0` change is backward compatible, but the `discover_configurations` call is now redundant.

fix(haskell): remove now redundant `discover_configurations` call

---

lua/astrocommunity/indent/mini-indentscope/init.lua

Brings over upstream v4 checks to correctly disable indentscope on special buftypes and terminals: https://github.com/AstroNvim/AstroNvim/commit/48298253d7df1599797b6a754fa95357d2ce15e1
-->
None

fix(mini-indentscope): correctly disable indentscope in buftypes and terminals

---

lua/astrocommunity/pack/haskell/init.lua

This PR is stacked on top of #570, which should be merged first.
- As discussed in https://github.com/AstroNvim/astrocommunity/pull/553#issuecomment-1705684907, the haskell-tools plugin is not user-configurable
- This PR uses [the same method as the java package](https://github.com/mrcjkb/astrocommunity/blob/82e76559973205eb9c8bd76ee134d3bccdee75b6/lua/astrocommunity/pack/java/init.lua#L36) to allow users to configure the plugin through an `opts` table in `community.lua`.
As mentioned in https://github.com/AstroNvim/astrocommunity/pull/553, I don't feel strongly about this, so please close this PR if you don't agree with this approach.

fix(haskell): make haskell-tools respect the `options` table

---

lua/astrocommunity/colorscheme/poimandres-nvim/init.lua
lua/astrocommunity/completion/tabnine-nvim/init.lua
lua/astrocommunity/pack/ruby/init.lua
lua/astrocommunity/project/project-nvim/init.lua

When configuring plugin specifications, sometimes the main module of the plugin doesn't match the name of the repository. Previously we would use `name` to set the name of the main module but what this is actually doing is changing the name of the plugin when it is cloned. This can make it harder for the user to know what name to use when overriding the provided configuration. `lazy.nvim` provides a separate configuration option, `main`, which lets you just set the name of the main module in which the `setup` function is called. This is a much cleaner approach and we should utilize it 99% of the time when the module doesn't match the repository.
There are a couple cases left in AstroCommunity where `name` is used and this is mainly when the repository name is completely wrong for what it …

refactor(main): Prefer using `main` instead of `name`

---

lua/astrocommunity/markdown-and-latex/peek-nvim/init.lua

Due to https://github.com/toppair/peek.nvim/issues/47, peek.nvim is unusable without https://github.com/toppair/peek.nvim/pull/50, this PR proposes to change the remote in order for the plugin to work

fix(peek-nvim): Swap remote of peek-nvim to fork

---

lua/astrocommunity/project/projectmgr-nvim/init.lua

just copy the projectmgr.nvim config and paste to my astro config, but got error like belowa
```
E5108: Error executing lua: ...hare/nvim/lazy/projectmgr.nvim/lua/projectmgr/manage.lua:50: attempt to index field 'config' (a nil value)
stack traceback:
...hare/nvim/lazy/projectmgr.nvim/lua/projectmgr/manage.lua:50: in function 'close_project'
...hare/nvim/lazy/projectmgr.nvim/lua/projectmgr/manage.lua:16: in function 'open_project'
...lazy/projectmgr.nvim/lua/projectmgr/telescope_picker.lua:46: in function 'run_replace_or_original'
...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:253: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:252>
```
Astro version: 3.37.6
Nvim …

fix(projectmgr-nvim): disable lazy loading

---

lua/astrocommunity/editing-support/rainbow-delimiters-nvim/init.lua

Breaking change in [f1ce55edcbd2c25a544c93357c66d4172a870766](https://github.com/HiPhish/rainbow-delimiters.nvim/commit/f1ce55edcbd2c25a544c93357c66d4172a870766)

fix(rainbow-delimiters-nvim): fix setup function due to breaking change 

---

lua/astrocommunity/bars-and-lines/smartcolumn-nvim/init.lua

Adds two filetypes (alpha, neo-tree) to the "smartcolumn" plugin's default list of disabled_filetypes (help, text, markdown). As both alpha-nvim and Neo-tree are included in the AstroNvim core and I see no reason why anyone would want a column in either case, I think it's a good idea to add them to the list of disabled filetypes.
This is the current behavior:
This is after the change:

fix(smartcolumn-nvim): Add sensible default opts for when not to show colorcolumn

---

lua/astrocommunity/file-explorer/oil-nvim/init.lua

`oil.nvim` is equipped to handle `oil-ssh://`, as demonstrated [here](https://github.com/stevearc/oil.nvim#ssh).
However, attempting to lazy load it may result in an error when using `nvim oil-ssh//xxx`.

fix(oil-nvim): ssh support

---

lua/astrocommunity/editing-support/ultimate-autopair-nvim/init.lua

Fixes the config for `ultimate-auto-pair` to work with the latest version and also pins the version at 0.6 to avoid future breaking changes (this is also recommended by the plugin).

fix(ultimate-autopair-nvim): Fix breaking changes in config, and pin plugin version to 0.6

---

lua/astrocommunity/git/octo-nvim/init.lua

Previously 'Resume review' was 'Start resume', this switch makes for a more intuitive description and aligns the first letter with the mapping. Not a big deal in the long run but I took way too long to find that mapping so figured a tiny PR wouldn't hurt :)

fix(octo-nvim): adjusted whichkey description mapping

---

lua/astrocommunity/pack/haskell/README.md
lua/astrocommunity/pack/haskell/init.lua

Adding netotest-haskell, haskell-snippets and **optionally** telescope-hoogle.
Basing my changes on how @mrcjkb [implemented it on lazyvim](https://github.com/LazyVim/LazyVim/pull/2052).
Since hoogle is an optionally recommended requirement for haskell-tools, the README reflects that and add instructions on how to enable the pack to install it and configure it properly.

feat(haskell): add neotest-haskell, haskell-snippets, telescope-hoogle to pack

---

lua/astrocommunity/pack/swift/README.md
lua/astrocommunity/pack/swift/init.lua

fixing an issue where:
- enabling  `{ import = "astrocommunity.pack.swift" },`
- enabling `lsp = { servers = { "sourcekit"} }` (not installed with mason)
- would trigger this error:
`[lspconfig] Cannot access configuration for sourcekit-lsp. Ensure this server is listed in "server_configurations.md" or added to a custom server.`

fix(swift): fix LSP handler error

---

lua/astrocommunity/pack/rust/init.lua

- enable cmp to crates and clean unused code

fix(rust): enable cmp to crates and remove `clang` handler disabling

---

lua/astrocommunity/split-and-window/mini-map/README.md
lua/astrocommunity/split-and-window/mini-map/init.lua

Adding mini.map plugin. 100% Lua, no external dependencies but GitSigns (as optional).
@Uzaaft I left autocmd out of the picture, feel free to modify the readme for instructions or the init if you think it should be the default. If you do the latter it should be perhaps configurable on/off? I can help tomorrow.
I was so frustrated with minimap (the rust one), its conflicts, and its bugs, that I seeked for an alternative so desperately. I finally found a GREAT ONE called mini.map :)
It works ridiculously well, it's extremley fast and lightweight, and it can double as a sidebar too! 100% Lua, no external dependencies (bar gitsigns if one wants to integrate it), and forget about brittle changes and stitches to make it compatible. it just works!!!

feat(split-and-window): Add mini-map

---

lua/astrocommunity/pack/swift/README.md
lua/astrocommunity/pack/swift/init.lua

Moving away from any XCode tooling in Swift Lang pack. See: https://github.com/AstroNvim/astrocommunity/discussions/669#discussioncomment-7752199
I am aware that opinionated is against the Astrocommunity guidelines. However, this pack **has** to be opinionated to make any sense. Otherwise the only thing in it would be treesitter. Not much to offer, really.
While not standardized (not for lack of trying), SwiftLint and SwiftFormat (not the Apple one) appear to be widely accepted by the community. They offer great customization too, in their own `.dotfiles` and it's an approach widely used by the community.
I'd say that until Apple (or the community) sets on a standard, this is the best we could do.

feat(swift): mv to swift only support (no xcode tooling here)

---

lua/astrocommunity/editing-support/auto-save-nvim/init.lua

The fork repo http://github.com/zoriya/auto-save.nvim has been deleted by its owner, revert to the original repo.

fix(editing-support): replace auto-save.nvim's url with its original repo

---

lua/astrocommunity/pack/typst/README.md
lua/astrocommunity/pack/typst/init.lua

Add typst pack mentioned in #652

feat(pack): Add typst pack

---

lua/astrocommunity/lsp/nvim-lsp-file-operations/README.md
lua/astrocommunity/lsp/nvim-lsp-file-operations/init.lua

This adds the [nvim-lsp-file-operations](https://github.com/antosha417/nvim-lsp-file-operations) plugin to the lsp category. It includes integration into neo-tree and nvim-tee.

feat(lsp): add `nvim-lsp-file-operations` plugin

---

lua/astrocommunity/editing-support/dial-nvim/init.lua

fixing mapping to the new syntax of dial.nvim
https://github.com/monaqa/dial.nvim#usage

fix(dial-nvim): change to new mapping api and adding g<C-x> g<C-a> mappings

---

lua/astrocommunity/editing-support/refactoring-nvim/init.lua

Before this, I got a module not found error. Wrapping it in a function, the require call is deferred until the keypress is run where the module is now available

fix(editing-support): wrap all require calls to refactoring in function

---

lua/astrocommunity/editing-support/true-zen-nvim/init.lua

Happy New Year!!!
fix(editing-support): removing mode from key mapping in true-zen-nvim as it is not valid

fix(true-zen-nvim): removing mode from key mapping in true-zen-nvim as it is not valid

---

lua/astrocommunity/editing-support/rainbow-delimiters-nvim/init.lua

addresses: https://github.com/AstroNvim/astrocommunity/issues/672
currently rainbow-delimiters do not load properly unless `:e` is run in the document. using VeryLazy event, it loads properly. I don't fully understand this, but I believe loading the file first then having rainbow-delimiters load causes it to not color everything properly. https://github.com/HiPhish/rainbow-delimiters.nvim/issues/31#issuecomment-1694775091. the `:e` fix seems to be known by the author

fix(rainbow-delimiters-nvim): event loading

---

lua/astrocommunity/test/nvim-coverage/init.lua

changed requires to dependencies as per lazy.nvim
Changes init.lua in test/nvim-coverage

fix(nvim-coverage): updated old keyword

---

lua/astrocommunity/pack/typescript/README.md
lua/astrocommunity/pack/typescript/init.lua

This uses the new notation in AstroLSP for setting up autocommands when attaching a language server. This makes it easy for users to opt out of the "ESLintFixAll" autocommand with something like this in their user plugins:
```lua
return {
"AstroNvim/astrolsp",
opts = {
autocmds = {
eslint_fix_on_save = false
}
}
}
```

refactor(typescript): set autocmd with AstroLSP

---

lua/astrocommunity/pack/blade/README.md
lua/astrocommunity/pack/blade/init.lua

This adds a language pack for Laravel Blade. Targeted for AstroNvim v4 just because it does use a custom language server. We could make a pack in v3 that just provides the nnull-ls and treesitter, but seems like most of the benefit would come from the LSP.

feat(pack): add `blade` pack for Laravel Blade support

---

lua/astrocommunity/comment/mini-comment/init.lua

While the pre-hook appears to work, `custom_commentstring` is recommended: <https://github.com/JoosepAlviste/nvim-ts-context-commentstring/wiki/Integrations#minicomment>
From the recommended configuration, the `autocmd` should also be turned off

refactor(comment): update mini.comment using custom_commentstring

---

lua/astrocommunity/pack/typescript-all-in-one/init.lua
lua/astrocommunity/pack/typescript-deno/init.lua

The typescript packs `all-in-one` and `deno` use an incorrect method to get lsp options from AstroLsp. This PR updates them to use the `lsp_opts` method to get the server configuration.

fix(pack): use lsp_opts to get server config for typescript

---

lua/astrocommunity/pack/angular/init.lua

https://github.com/nvim-treesitter/nvim-treesitter-angular is deprecated (and archived) since Angular support is included in `nvim-treesitter` itself.
Without this fix, currently running `:TSUpdate angular` fails with:
```
nvim-treesitter[angular]: Error during tarball extraction.                                                                                                                                     
tar: Error opening archive: Unrecognized archive format  
``` 
It almost seems unrelated, but it is https://github.com/nvim-treesitter/nvim-treesitter/issues/5246

feat(angular): Migrate to built-in treesitter

---

lua/astrocommunity/motion/hop-nvim/README.md

The init.lua file has been updated to point to the fork by smoka7, but the README still points to the original.

docs(hop-nvim): Point repo URL to correct repository

---

lua/astrocommunity/media/image-nvim/README.md
lua/astrocommunity/media/image-nvim/init.lua

I recently came across this nvim plugin:
https://github.com/3rd/image.nvim
Which can display images in astronvim via kittys image protocol, which is neat!
Works very well and also prevents astronvim from crashing when opening images :).
It has some requirements, so it does not work out of the box though.
I have only tested it with kitty.
Happy to discuss it or change something if it seems wrong.

feat(media): add image.nvim

---

lua/astrocommunity/pack/go/init.lua

This replace `x-ray/go.nvim` with a much more simpler alternative `olexsmir/gopher.nvim`.

fix(pack): disable `go.nvim` defaults to prevent conflicts

---

lua/astrocommunity/git/diffview-nvim/init.lua

This fixes an issue where the default AstroNvim `winbar` causes rows to be misaligned. This also disables the default view activation so that AstroNvim doesn't try to restore cursor position and fold state when entering buffers.

fix(diffview-nvim): use diffview winbar and disable view activation

---

lua/astrocommunity/motion/mini-surround/init.lua

Non-core plugins shouldn't be disabled. Someone would have to explicitly add both plugins to encounter any issues.

chore(mini-surround): remove disabling of vim-sandwich

---

lua/astrocommunity/utility/mason-tool-installer-nvim/README.md
lua/astrocommunity/utility/mason-tool-installer-nvim/init.lua

This adds `mason-tool-installer` as an alternate mechanism for ensuring things are installed. This also adds integration with the other installer helper plugins that lets them work together nicely.

feat(utility): add `mason-tool-installer.nvim` installation utility

---

lua/astrocommunity/editing-support/conform-nvim/init.lua
lua/astrocommunity/lsp/nvim-lint/init.lua

This makes `conform.nvim` and `nvim-lint` play nicely with `null-ls` without having to fully disable it.

Allow `conform.nvim` and `nvim-lint` to work alongside `mason-null-ls`

---

lua/astrocommunity/motion/harpoon/init.lua

tested with minimal v3 install.. but not actually using it. so i hope it works :D

feat(harpoon): Update to v2

---

lua/astrocommunity/git/neogit/init.lua

The entry for neogit in which-key was off, the main git menu entry was overwritten and no icon/description was set for the neogit sub-menu. Simple fix by modifying key mappings.

fix(neogit): set correct neogit menu entry in which-key

---

lua/astrocommunity/pack/bash/README.md
lua/astrocommunity/pack/bash/init.lua
lua/astrocommunity/pack/lua/README.md
lua/astrocommunity/pack/lua/init.lua
lua/astrocommunity/pack/python-ruff/init.lua
lua/astrocommunity/pack/quarto/init.lua
lua/astrocommunity/pack/typescript/init.lua

I started getting deprecation warnings from `null-ls`. It seems `null-ls` wants to clean unmaintained builtins, see: https://github.com/nvimtools/none-ls.nvim/issues/58
This PR replaces some of the deprecated builtins with the suggested alternatives, but is by no means exhaustive. For example, I am not sure about `eslint`, as I don't use it.

fix(pack): replace deprecated none-ls builtins

---

lua/astrocommunity/markdown-and-latex/markdown-preview-nvim/init.lua

**Issue**
- iamcco/markdown-preview.nvim#616
In the process of updating (lazy sync), an error is provoked where it says markdown-preview.nvim is broken, this is caused by unstashed edit by npm in plugins cloned directory. This has been common problem which is caused **npm**. The actual issue can be found [here](https://github.com/iamcco/markdown-preview.nvim/issues/616).
**Error:**
```
You have local changes in `/.../.local/share/nvim/lazy/markdown-preview.nvim`:
* app/yarn.lock
Please remove them to update.
You can also press `x` to remove the plugin and then `I` to install it again.
```

fix(markdown-preview-nvim): yarn istead of npm

---

lua/astrocommunity/lsp/ts-error-translator-nvim/README.md
lua/astrocommunity/lsp/ts-error-translator-nvim/init.lua

This adds the new [ts-error-translator.nvim](https://github.com/dmmulroy/ts-error-translator.nvim) plugin with some pretty nice lazy loading all the way up until a diagnostic message is published by a supported language server

feat(lsp): add `ts-error-translator.nvim` with nice lazy loading

---

lua/astrocommunity/pack/templ/README.md
lua/astrocommunity/pack/templ/init.lua

This adds a pack for the [Templ](https://templ.guide/) HTML templating language

feat(pack): add Templ language pack

---

lua/astrocommunity/motion/grapple-nvim/init.lua

Hello, again 👋 
I received a bit of feedback after releasing the rewrite the other day. Thought I would send one more PR to address that here as well 🙂 
- Add `nvim-tree/nvim-web-devicons` as a lazy (optional) dependency
- Use `toggle_*` instead of `open_*` so Grapple windows can be open/closed with the same mapping

feat(grapple-nvim): better keymaps + add nvim-web-devicons dependency

---

lua/astrocommunity/lsp/coc-nvim/init.lua

Add `<leader>l;` to format selected lines in visual mode.
I believe `<leader>;` would be more natural here, but I opted to follow the mnemonic as it was already established

feat(coc): add v-mode selection format

---

lua/astrocommunity/utility/telescope-coc-nvim/README.md
lua/astrocommunity/utility/telescope-coc-nvim/init.lua

Add `fannheyward/telescope-coc.nvim` extension for users who use Telescope and CoC

feat(coc): add extension for telescope.nvim

---

lua/astrocommunity/lsp/coc-nvim/README.md
lua/astrocommunity/lsp/coc-nvim/init.lua
lua/astrocommunity/utility/telescope-coc-nvim/README.md
lua/astrocommunity/utility/telescope-coc-nvim/init.lua

Closes #657 
This adds `coc.nvim` as an option for LSP and completion. This disables all other LSP functionality.

feat(lsp): add `coc.nvim`

---

lua/astrocommunity/pack/rust/init.lua

Setting the version for rustaceanvim to ^v4 since it's recommended by the maninater 
I'm not sure if this will introduce breaking changes this is what is listed in the release note

chore(rust): pin rustaceanvim to ^v4 

---

lua/astrocommunity/pack/bash/init.lua

While using the bash pack, I came across a this odd behavior: Bash diagnostics showing up as duplicates: 
This takes place because, as referenced [here](https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/951#discussioncomment-3141217) and [here](https://github.com/bash-lsp/bash-language-server/commit/71c6a4ae2891cdbdfbbfb8ca0d11a566c900f6d2), `bash-ls` has a shellcheck integration by default. So there is no need to set it up as a secondary source. 
This PR removes `shellcheck` from the list of language servers installed by mason to be configured and used by null-ls/none-ls

fix(bash): fix duplicate diagnostics in bash pack

---

lua/astrocommunity/completion/coq_nvim/init.lua

After coq is lazy loaded, meaning after the first autocompletion is triggered, it's default binding `<C-h>` for `jump_to_mark` (https://github.com/ms-jpq/coq_nvim/blob/coq/docs/SNIPS.md#snippets) clashes with AstroNVims window movement. Basically, as soon as coq is loaded, you can't switch to the left window anymore.
This is an attempt to fix that. I chose `<C-t>` to jump to the next snippet edit, which is absolutely a debatable choice. I think this clashes the least with both AstroNVims and Neovims default bindings.

fix(coq_nvim): fix coq bindings

---

lua/astrocommunity/lsp/ts-error-translator-nvim/init.lua

The Svelte and Astro language servers are running `tsserver` under the hood so we should also enable this when `svelte` support gets added to ts-error-transltor.nvim.
Dependent on: https://github.com/dmmulroy/ts-error-translator.nvim/pull/26

feat(ts-error-translator-nvim): `svelte` and `astro` support added

---

lua/astrocommunity/editing-support/yanky-nvim/init.lua

Closes #830 
Map the yanky.nvim/Telescope yank history picker to <kbd>&lt;Leader&gt;fy</kbd> (mnemonic: “find yanks”) and change its description to `Find yanks`.

fix(yanky-nvim)!: change conflicting mapping `<Leader>p` → `<Leader>fy`

---

lua/astrocommunity/startup/mini-starter/README.md
lua/astrocommunity/startup/mini-starter/init.lua

Added ['mini-starter'](https://github.com/echasnovski/mini.starter) plugin and configured it for Astronvim.
Disabled the alpha plugin and configured the buffer close command to open nvim-starter when all buffers are closed.

feat(startup): add mini-starter plugin

---

lua/astrocommunity/utility/mason-tool-installer-nvim/init.lua

Replaces `null_ls_to_package` mappings table with `mason-null-ls`'s provided `getPackageFromNullLs` function for mapping package names to Mason names.
* Link to mason-null-ls function used: [here](https://github.com/jay-babu/mason-null-ls.nvim/blob/main/lua/mason-null-ls/mappings/source.lua#L23-L27)
- This function uses the `null_ls_to_package` table under the hood while also fixing the names of package names following "normal" conventions
- This function was introduced [here](https://github.com/jay-babu/mason-null-ls.nvim/pull/40/files) and a lot of "normal" mappings (including `clang_format` -> `clang-format`) got removed from the mapping sources as a result
* This provides an alternative fix to the issue I was having in https://github.com/AstroNvim/astrocommunity/pull/837

fix(mason-tool-installer-nvim): Use mappings function for null-ls names

---

lua/astrocommunity/media/image-nvim/README.md
lua/astrocommunity/media/image-nvim/init.lua

Change the image.nvim plugin init.lua to use luarocks.nvim for adding the "magick" rock. Removes a step from the installation.
It adds luarocks.nvim as a dependency

feat(image-nvim): use luarocks.nvim for "magick" rock

---

lua/astrocommunity/editing-support/nvim-devdocs/init.lua

Previously, executing `:DevdocsOpenCurrentFloat` in a typescript file would only provide the Typescript docs. This is desirable, but most of the docs TS devs are interested in are normally under `javascript` (MDN) or `node`. You could work around this by opening up all docs, but if you use multiple languages docs, this could be a cumbersome experience.
This change bundles all three sets of docs to be available under current `ts` floats, which should be a sane default for 99% of devs.

feat(nvim-devdocs): bundled `js/node` docs for typescript files

---

lua/astrocommunity/pack/rust/README.md

[] Not Completed
--> [x] Completed
The Rust pack already uses the rustacenvim plugin instead of the rust-tools.nvim plugin, since that is deprecated.
The configuration uses cargo clippy, the most sensible default in my opinion, the paragraph detailing how it can be setup is useless.

docs(rust): Update docs to reflect the pack

---

lua/astrocommunity/recipes/neo-tree-dark/README.md
lua/astrocommunity/recipes/neo-tree-dark/init.lua

Add dark themed color scheme for `neo-tree.nvim`

feat(recipes): add `neo-tree` dark theme recipe

---

lua/astrocommunity/git/blame-nvim/init.lua

fix(blame-nvim): Align the git blame window properly when using heirline

---

lua/astrocommunity/pack/python/init.lua

fix incorrect path for windows debugpy.
The path for installing debugpy on Mason under Windows is`~/<mason pkg path>/debugpy/venv/Scripts/python.exe`

fix(python): incorrect path for windows debugpy

---

lua/astrocommunity/editing-support/mini-operators/README.md
lua/astrocommunity/editing-support/mini-operators/init.lua

Making this a draft PR, because i am unsure which binding would match it neatly. I left there also an note on the source code.

feat(editing-support): add `mini-operators` plugin

---

lua/astrocommunity/programming-language-support/rest-nvim/init.lua

Update needed as [rest.nvim](https://github.com/rest-nvim/rest.nvim) v2 has been released. Followed instructions in their README.
- Dependencies changed: `vhyrro/luarocks.nvim` added [[ref](https://github.com/rest-nvim/rest.nvim/blob/fd16650a55fb1035c82e15484edd514bf6c66a3c/README.md#lazynvim)]
- Command and keybindings updated [[ref](https://github.com/rest-nvim/rest.nvim/blob/fd16650a55fb1035c82e15484edd514bf6c66a3c/README.md#keybindings)]
- Treesitter parser list updated [[ref](https://github.com/rest-nvim/rest.nvim/blob/fd16650a55fb1035c82e15484edd514bf6c66a3c/README.md#tree-sitter-parsing)]

fix(rest-nvim)!: update to rest.nvim v2

---

lua/astrocommunity/markdown-and-latex/markmap-nvim/init.lua

* Also place `"Zeioth/markmap.nvim"` with specs inside brackets.
* And load only with markdown files.

fix(markmap-nvim): Fix issue with pack due to wrongly named null-ls package, and load on `md` file

---

lua/astrocommunity/diagnostics/trouble-nvim/README.md
lua/astrocommunity/diagnostics/trouble-nvim/init.lua

feat(trouble-nvim): add mappings for `todo-comments.nvim`

---

lua/astrocommunity/editing-support/neogen/init.lua

Keyboard shortcut **(leader + a + CR)** for automatic comment generation did not correctly detect element type (function, class, etc.). This commit fixes the bug so that the shortcut correctly detects element type and generates the appropriate comment.
The "keymap" **(leader + a + CR)** that triggers the automatic neogen generation does not work and throws an error message saying "current type is not supported".
https://github.com/AstroNvim/astrocommunity/assets/51010598/e9d9cabf-54be-4b6e-a7c0-ca116e988fcb
https://github.com/AstroNvim/astrocommunity/assets/51010598/5d63fa71-c803-48f0-aa32-50dfcf0e9da8

fix(neogen): keymap for type-aware automatic comment generation

---

lua/astrocommunity/git/blame-nvim/init.lua

The blame.nvim plugin has been rewritten and "broke" this spec. Updated to this state https://github.com/FabijanZulj/blame.nvim/tree/39f6123b78bde45917de071a07eba17b136d9f2c.

fix(blame-nvim): adjust to the new rewrite

---

lua/astrocommunity/pack/sql/README.md
lua/astrocommunity/pack/sql/init.lua

`sqls` supports formatting so we don't need to add `sqlfluff`.

fix(sql): drop `sqlfluff` as `sqls` supports formatting

---

lua/astrocommunity/pack/fish/init.lua

If `opts.sources` is not a table (or didn't exist, for that matter), fish linter and formatter didn't get added, they now do.

fix(fish): none-ls `opts.sources` not being created if it doesn't exist

---

lua/astrocommunity/pack/rust/README.md

Hi, I don't really think this is necessary to add to the README.

docs(rust): Remove unnecessary disclaimer

---

lua/astrocommunity/note-taking/venn-nvim/README.md
lua/astrocommunity/note-taking/venn-nvim/init.lua

Draw ASCII diagrams easily in Neovim
Added new plugin with necessary configuration per the author

feat(note-taking): Add venn-nvim

---

lua/astrocommunity/editing-support/multiple-cursors-nvim/README.md
lua/astrocommunity/editing-support/multiple-cursors-nvim/init.lua

This adds the plugin [`multiple-cursors.nvim`](https://github.com/brenton-leighton/multiple-cursors.nvim)

feat(editing-support): add `multiple-cursors.nvim`

---

lua/astrocommunity/completion/tabby-nvim/README.md
lua/astrocommunity/completion/tabby-nvim/init.lua

Closes #872
Instructions to use Tabby for an open-source, self-hosted AI coding assistant. With Tabby, every team can set up its own LLM-powered code completion server with ease.
I added some steps for installing on Linux with Docker as [Tabby Docs](https://tabby.tabbyml.com/docs/getting-started) demonstrate particularly methods for Windows/Mac. However, maybe this is more suited to putting in their repo? Or maybe the user is just expected to figure this out on their own as Docker is agnostic... Let me know what you think
Otherwise, just want to make sure that the key-bindings are appropriate. I assume <tab> is likely to be conflicting...

feat(completion): Add `vim-tabby`

---

lua/astrocommunity/pack/tailwindcss/init.lua

The tailwindcss-language-server is currently always up and running. I believe it should only run when a Tailwind CSS config is found. 
This PR fixes that.

fix(tailwindcss): add root_dir detection to tailwindcss pack

---

lua/astrocommunity/pack/cpp/init.lua

<leader>lw to sWitch between source and header.
"w" isn't assigned to any other key currently.
Caveat: The keybinding will stay for all LSP although only Clangd supports it. Ideally the keybinding should appear only for buffers Clangd is attached.

feat(cpp): Add `<Leader>lw` keymap to switch between source and header

---

lua/astrocommunity/lsp/actions-preview-nvim/init.lua
lua/astrocommunity/pack/elixir-phoenix/init.lua
lua/astrocommunity/pack/elm/init.lua
lua/astrocommunity/pack/fish/init.lua
lua/astrocommunity/pack/gleam/init.lua
lua/astrocommunity/pack/just/init.lua
lua/astrocommunity/pack/nim/init.lua
lua/astrocommunity/pack/pkl/init.lua
lua/astrocommunity/pack/templ/init.lua
lua/astrocommunity/pack/typescript-all-in-one/init.lua
lua/astrocommunity/pack/typescript-deno/init.lua

In the pack typescript-all-in-one disable typescript-tools and tsserver to denols. Apparently tsserver is disabled but typescript-tools keeps tsserver errors active again.

fix(pack): update typescript-all-in-one disable typescript-tools to denols

---

lua/astrocommunity/pack/typst/init.lua

This adds the ability to manually build the binaries for typst-preview.nvim in case it have failed doing so with lazy

fix(typst): added missing command to typst-preview.nvim

---

lua/astrocommunity/pack/tailwindcss/init.lua

#912 caused the Tailwind LSP to not work, when using the tailwindcss-rails Ruby gem.
The tailwindcss-rails Ruby gem keeps the config at config/tailwind.config.js, which is not in the new `root_dir` config.
https://github.com/rails/tailwindcss-rails?tab=readme-ov-file#configuration-and-commands

fix(tailwindcss): fix TailwindCSS pack not loading when using tailwindcss-rails Ruby Gem

---

lua/astrocommunity/git/gitlinker-nvim/README.md

The link was to the incorrect repo which would lead to using the wrong documentation for configuration

fix(gitlinker-nvim): Point repository link to correct repository

---

lua/astrocommunity/keybinding/hydra-nvim/README.md
lua/astrocommunity/keybinding/hydra-nvim/init.lua
lua/astrocommunity/note-taking/venn-nvim/init.lua

This adds `Hydra.nvim` and provides an API for configuring it through the `opts` table. This could be useful for AstroCommunity entries to create submenus if hydra is available
I removed the automatic lazy loading based on keys because it is hyper unstable based on how the `body` + `heads` work. It's also not very slow to load so it's ok to just load it on `VeryLazy` like we do which-key

feat(hehe): add `Hydra.nvim`

---

lua/astrocommunity/file-explorer/mini-files/init.lua

A small change so that mini.files toggles when pressing `<leader>e` just as neotree in vanilla astronvim.
(really sorry for the f-up earlier)

feat(mini-files): replicate toggling behaviour of astronvim neotree

---

lua/astrocommunity/note-taking/global-note-nvim/README.md
lua/astrocommunity/note-taking/global-note-nvim/init.lua

Added a plugin for global-note.nvim
Also added a command for opening a project-local note

feat(note-taking): added global-note.nvim plugin

---

lua/astrocommunity/motion/harp-nvim/harp-nvim.lua

Transferred plugin ownership, so updated the spec to point to the new/transferred repo
This is in conjunction with some plugin updates for more advanced use of harp itself, none of which require further changes beyond pointing to the new repo as far as I am aware.

fix(harp-nvim): Updated spec for plugin repo transfer

---

lua/astrocommunity/color/transparent-nvim/init.lua

As suggested by the title, transparent keymap is actually not working. This pr is a one line fix to make it works!

fix(transparent-nvim): transparent keymap

---

lua/astrocommunity/pack/rego/README.md
lua/astrocommunity/pack/rego/init.lua

Waiting for `regols` support to be added to `mason-lspconfig` and a release to be tagged:
- https://github.com/williamboman/mason-lspconfig.nvim/pull/403
- https://github.com/williamboman/mason-lspconfig.nvim/pull/410

feat(pack): add Rego language pack

---

lua/astrocommunity/pack/lean/README.md
lua/astrocommunity/pack/lean/init.lua

This PR adds language support for the [Lean theorem prover](https://leanprover.github.io) via the [`lean.nvim`](https://github.com/Julian/lean.nvim) extension.
This is an intentionally trivial PR to get my feet wet with config upstreaming :)
The `lean.nvim` plugin explicitly requires an `on_attach()` callback to be set, so I relied on the `astrolsp`-provided one.

feat(pack): add Lean language pack

---

lua/astrocommunity/pack/typescript/init.lua

This leverages AstroCore's built in `rooter` module to improve the `prettier` detection. It will search up to detect `prettier` configuration files moving up the filesystem to handle being inside a nested folder. This also adds LSP integration by checking for `package.json` files inside of all LSP working directories along with the current directory

fix(typescript): improve `prettier` detection with `astrocore.rooter`

---

lua/astrocommunity/completion/copilot-cmp/README.md
lua/astrocommunity/completion/copilot-cmp/init.lua

Adds a new way to integrate copilot with cmp, besides the current options available. This one puts copilot within cmp, instead of setting it up in parallel with it.

feat(completion): add `copilot-cmp`

---

lua/astrocommunity/pack/rust/init.lua

`checkOnSave` is supposed to be a boolean: https://rust-analyzer.github.io/manual.html#rust-analyzer.checkOnSave
The right place to put `command = "clippy"` is under `check`: https://rust-analyzer.github.io/manual.html#clippy

fix(rust): Fix rust-analyzer check to clippy

---

lua/astrocommunity/pack/rust/init.lua

merge astrolsp settings in such a way as to preserve the default behavior of loading local project settings from rust-analyzer.json
The default behavior of rustaceanvim is to load a `rust-analyzer.json` at the project root to load rust-anlyzer settings
see:
[rustaceanvim/config/server.lua#L15](https://github.com/mrcjkb/rustaceanvim/blob/b5d6ac50b3f87a6e8fae27cb8d8e49a6ca653aa6/lua/rustaceanvim/config/server.lua#L15)
[rustaceanvim/config/internal.lua#L287](https://github.com/mrcjkb/rustaceanvim/blob/b5d6ac50b3f87a6e8fae27cb8d8e49a6ca653aa6/lua/rustaceanvim/config/internal.lua#L287)
this file can have any of the keys defined in https://rust-analyzer.github.io/manual.html#configuration
either at the top level of the json or under a `'rust-analyzer'` top level key
This is done by having …

fix(rust): preserve loading of rust-analyzer.json

---

lua/astrocommunity/bars-and-lines/dropbar-nvim/init.lua
lua/astrocommunity/bars-and-lines/vim-illuminate/init.lua
lua/astrocommunity/code-runner/overseer-nvim/init.lua
lua/astrocommunity/color/headlines-nvim/init.lua
lua/astrocommunity/color/mini-hipatterns/init.lua
lua/astrocommunity/colorscheme/mini-base16/init.lua
lua/astrocommunity/comment/mini-comment/init.lua
lua/astrocommunity/diagnostics/trouble-nvim/init.lua
lua/astrocommunity/editing-support/mini-splitjoin/init.lua
lua/astrocommunity/editing-support/nvim-ts-rainbow2/init.lua
lua/astrocommunity/editing-support/rainbow-delimiters-nvim/init.lua
lua/astrocommunity/file-explorer/mini-files/init.lua
lua/astrocommunity/git/neogit/init.lua
lua/astrocommunity/git/octo-nvim/init.lua
lua/astrocommunity/indent/mini-indentscope/init.lua
lua/astrocommunity/lsp/coc-nvim/init.lua
lua/astrocommunity/motion/harpoon/init.lua
lua/astrocommunity/motion/hop-nvim/init.lua
lua/astrocommunity/motion/leap-nvim/init.lua
lua/astrocommunity/motion/mini-ai/init.lua
lua/astrocommunity/motion/mini-basics/init.lua
lua/astrocommunity/motion/mini-bracketed/init.lua
lua/astrocommunity/motion/mini-move/init.lua
lua/astrocommunity/motion/mini-surround/init.lua
lua/astrocommunity/scrolling/mini-animate/init.lua
lua/astrocommunity/split-and-window/mini-map/init.lua
lua/astrocommunity/syntax/vim-sandwich/init.lua
lua/astrocommunity/test/neotest/init.lua
lua/astrocommunity/utility/noice-nvim/init.lua

i tried installing hop as astrocommunity package, and in the repo i saw that it had code that supposedly should automatically enable integration for hop in catppuccin theme. yet that didnt work for some reason, and so i just enabled it manually. and today after thinking about it and 10 minutes of experimenting i figured it out. to fix this, all you have to do is set `name = "catppuccin"`, then its going to work. i just took hop as an example, but its with every single astrocommunity package i tried. like mini-clue or trouble and so on.

fix(catppuccin): set name to "catppuccin"

---

lua/astrocommunity/pack/rust/init.lua

Prevent rustaceanvim from enabling clippy on it's own. This results in a bad config atm. and would clash with any user provided config / this packs config if it worked.
Add the `--no-deps` clippy arg to not lint dependencies by default
this would fix rustacenvim 's bad clippy config but we should still disable it because it on it's side because will overwrite ours when
`load_rust_analyzer_settings` is called
https://github.com/mrcjkb/rustaceanvim/pull/403

fix(rust): fix clippy config, add `--no-deps` arg

---

lua/astrocommunity/pack/go/init.lua

Currently, Neovim will freeze when installing/updating `go.nvim` due to the synchronous callback trying to install relevant Golang CLI devtools. This PR stops that from happening via an asynchronous callback instead.
cc https://github.com/ray-x/go.nvim/issues/433
I have locally tested this change on my machine using the following override:
```lua
-- astrocommunity.pack.go
{
"ray-x/go.nvim",
build = function() require("go.install").update_all() end,
},
```

fix(go): modify the `build` callback to avoid freezing on `go.nvim` installation

---

lua/astrocommunity/code-runner/conjure/README.md
lua/astrocommunity/code-runner/conjure/init.lua
lua/astrocommunity/editing-support/nvim-parinfer/README.md
lua/astrocommunity/editing-support/nvim-parinfer/init.lua
lua/astrocommunity/editing-support/nvim-treesitter-sexp/README.md
lua/astrocommunity/editing-support/nvim-treesitter-sexp/init.lua
lua/astrocommunity/pack/clojure/README.md
lua/astrocommunity/pack/clojure/init.lua

Provide both approaches to structural editing Clojure code (paredit & parinfer) and remove the more opinionated configurations for Conjure REPL client.
- add nvim-treesitter-sexp for slurp/barf style structured editing
- add ts-comments.nvim to support `;;` and `;` line & partial line comments (removing need for autocmd)
- drop the more opinionated conjure config overrides
- elaborate on use and overrides in readme
Conjure plugin will disable diagnostics in the REPL log (HUD), removing the need to define the autocmd to disable them.
> If you prefer I submit this as 4 separate PR's then let me know...

feat: add several new plugins and modularize the clojure pack

---

lua/astrocommunity/pack/typescript-all-in-one/init.lua
lua/astrocommunity/pack/typescript/README.md
lua/astrocommunity/pack/typescript/init.lua

This moves from `typescript-tools.nvim` to `vtsls` language server. Let me know if this is desired, I feel like `typescript-tools` always has problems with users

feat(typescript)!: replace `typescript-tools` with `vtsls`

---

lua/astrocommunity/project/project-nvim/README.md

The plugin actually installed is [jay-babu/project.nvim](https://github.com/jay-babu/project.nvim) which is a fork of [ahmedkhalf/project.nvim](https://github.com/ahmedkhalf/project.nvim).
For users willing to override its configuration, it's better to have the correct link, since the fork may introduce incompatible changes.

docs(project-nvim): correct link to plugin repository

---

lua/astrocommunity/project/project-nvim/README.md

Adds a brief note to the project-nvim README.md file that AstroNvim contains a built-in Project Rooter, and if the community plugin is enabled, the built-in functionality will be disabled.
This PR originated from a discord conversation in the #astrocommunity channel.
> @rocode: Should community plugins have a note on them if their functionality was already upstreamed or incorporated into AstroCore? For example, I just realized I didn't need project-nvim after seeing the Project Rooter recipe in the docs, but trying to migrate over caused confusion because it isn't documented that it turns off the built-in functionality.
>[...]
>@mehalter: yeah that would be great! If you open a PR it would be good to note on that plugin (and maybe the other project plugins) that there is a new rooter in …

docs(project-nvim): add note about built-in functionality

---

lua/astrocommunity/editing-support/vim-visual-multi/init.lua

`AstroNvim/astrocore` dependencies name replacing incorrect `astronvim/astrocore` name
Causes `:checkhealth` to fail due to the same plugin being referred to by two different URLs

fix(vim-visual-multi): dependencies name correction

---

lua/astrocommunity/pack/java/init.lua

With the release of Neovim 0.10 we should enable inlay hints by default. Without this, toggling AstroNvim inlay hints (\<leader\>uh/\<leader\>uH) will not have any effect on Java project.

feat(java): enable inlay hints by default

---

lua/astrocommunity/lsp/lspsaga-nvim/README.md
lua/astrocommunity/lsp/lspsaga-nvim/init.lua

This adds `lspsaga.nvim` and replaces the internal LSP functionality with it's features where applicable

feat(lsp): add `lspsaga.nvim`

---

lua/astrocommunity/pack/vue/init.lua

Add Volar as a tsserver plugin, configured with vtsls.
In  [`volar >= 2.0`](https://github.com/vuejs/language-tools/tree/master/packages/typescript-plugin), some synchronization problems between tsserver and volar appear, causing errors when working with .ts and .vue files at the same time.
An issue for this is being tracked (yioneko/vtsls#148)

feat(vue): configure volar as tsserver plugin

---

lua/astrocommunity/bars-and-lines/bufferline-nvim/init.lua

Map `[b` and `]b` to the bufferline-specific calls for cycling buffers.
I included `astrocommunity.bars-and-lines.bufferline-nvim` and observed the `]b` and `[b` bindings not behaving correctly. They were switching buffers, but out-of-order w.r.t. how they were displayed in bufferline. This PR remaps those to call bufferline's specific API for cycling through tabs. With this custom binding added, I now observe the correct behavior.
It's not super straightforward to repro. Sometimes, I open a project, open various buffers, and press `]b` and the ordering is correct. Other times, after opening some buffers, say with `gd` or from telescope searches, the buffer navigation starts happening out of order.

fix(bufferline-nvim): add bufferline cycle bindings

---

lua/astrocommunity/pack/java/init.lua

`jdtls` changed the settings hierarchy; for instance, they moved `settings.completion` to `settings.java.completion`. 
This PR moved these settings.
This document described the most recent setting hierarchy:
[Jdtls Initialize Request](https://github.com/eclipse-jdtls/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request)

fix(java): update for the latest settings hierarchy

---

lua/astrocommunity/color/twilight-nvim/init.lua

Closes #1031(it's already closed...)
Change twilights keymap from `<leader>uT` to `<leader>uW`.

feat(twilight-nvim)!: Change keymap due to conflict with transparent-nvim

---

lua/astrocommunity/pack/cs/README.md
lua/astrocommunity/pack/cs/init.lua

Closes #951 
This is untested because I don't have a C# environment. @Cretezy this is the correct way to set it up, it's the same way you mentioned you tried it. If it doesn't work it could just be the plugin is broken and we shouldn't add it. Could you give this a try?

feat(cs): add `csharpls-extended-lsp.nvim` for better go to definition

---

lua/astrocommunity/recipes/auto-session-restore/README.md
lua/astrocommunity/recipes/auto-session-restore/init.lua

Adds auto-session-restore like in documentation, but also detect if nvim has been started with stdin redirected, like `stream | nvim` or like `export MAPAGER='nvim +Man!'; man man`.
The stdin detection is taken from https://github.com/thaerkh/vim-workspace/blob/master/plugin/workspace.vim#L268 .
Would be nice to add the stdin input handling also to documentation.

feat(recipes): add auto-session-restore

---

lua/astrocommunity/completion/cmp-under-comparator/README.md
lua/astrocommunity/completion/cmp-under-comparator/init.lua

Add cmp-under-comparator to completion.
I tried to make the position of the comparator in nvim-cmp what users would "expect", and follow recommendation like from [here](https://github.com/lukas-reineke/cmp-under-comparator/issues/3#issuecomment-2103690672). I think after "recently_used" is the best position, first the ones you used, then the ones not string with dash `_`.

feat(completion): add cmp-under-comparator

---

lua/astrocommunity/bars-and-lines/bufferline-nvim/init.lua

Since this import uses `astrocommunity.recipes.disable-tabline`, it disables all the `<leader>b` bindings too. This PR adds back the bufferline equivalents of those bindings.
Basically a continuation of #1009.
NOTE: I wasn't able to easily find an equivalent of `<leader>bC` to close _all_ buffers.
This takes all the default bindings from [the docs](https://docs.astronvim.com/mappings#buffers) with the exception of `<leader>bC`.

fix(bufferline-nvim): add back bufferline leader bindings

---

lua/astrocommunity/media/neocord-nvim/README.md
lua/astrocommunity/media/neocord-nvim/init.lua

This adds the new `neocord.nvim` plugin for discord presence.
The following repository supports astrovim as native client.

feat(media): add `neocord.nvim`

---

lua/astrocommunity/completion/nvim-cmp-buffer-lines/README.md
lua/astrocommunity/completion/nvim-cmp-buffer-lines/init.lua

Adds the `nvim-cmp-buffer-lines` nvim-cmp source, but instead of just adding it to normal completions, keeps it local to a hotkey.
The reasoning for this is that, even with a low priority, whole line completions end up being super annoying, when mixed in with all the other (usually more useful) suggestions. So it's for this reason that this source is effectively "opt-in".
The mapping used is `<C-x><C-l>`, because that's the default way to do whole line completions. What you basically get with this community pack, is you replace built in whole line completions with ones that use nvim-cmp.
The hotkey is wack, but it is default! So I think it makes the most sense, even if there could be other, more ergonomic mappings.
At the very least, if a person wants the functionality, but on a different …

feat(completion): add `nvim-cmp-buffer-lines`

---

lua/astrocommunity/pack/hyprland/README.md
lua/astrocommunity/pack/hyprland/init.lua

feat(pack): add hyprland config file language support

---

lua/astrocommunity/editing-support/chatgpt-nvim/init.lua

Chatgpt.nvim has mapping recommendation in their readme. I think it makes a nice addition under `<leader>G`, `G` like gpt. I typically use `<space>Gc` to start a chat. Let me know what you think.

feat(chatgpt-nvim): add which-key mappings below <leader>G

---

lua/astrocommunity/code-runner/vim-slime/README.md
lua/astrocommunity/code-runner/vim-slime/init.lua

This adds [`vim-slime`](https://github.com/jpalardy/vim-slime) with nice lazy loading as well as a `<Leader>` key driven menu. It also adds some automatic target detection out of the box and automatic configuration of markdown code cells to improve the out of the box experience.

feat(code-runner): add `vim-slime`

---

lua/astrocommunity/pack/tailwindcss/init.lua

After updating to new version which included [this PR](https://github.com/AstroNvim/astrocommunity/pull/912) I noticed my tailwind intellisense stopped working and `:LspInfo:` shows that rootDir was not found.
I spotted that mentioned above PR didn't include .mjs extension which I use in my projects for tailwind config files.

fix(tailwindcss): add mjs support for tailwind root dir detection

---

lua/astrocommunity/completion/codeium-vim/init.lua

fix(codeium-vim): port mappings to `astrocore` and fix lazy loading event

---

lua/astrocommunity/pack/blade/README.md

Avoids cases like #1081  where people are too lazy to search themselves.

docs(blade): Add inn link for laravel-dev-generators

---

lua/astrocommunity/lsp/nvim-lsp-endhints/init.lua

We tried AstroLsp, but seems that the event loading proposed by the plugin maintainer is the way to go.

fix(nvim-lsp-endhints): Fix issue with loading of plugin due to event

---

lua/astrocommunity/pack/typst/README.md

Fix the `typst.vim` name typo in pack/typst/README.md

docs(typst): Fix typo

---

lua/astrocommunity/editing-support/vim-doge/README.md
lua/astrocommunity/editing-support/vim-doge/init.lua

feat(editing-support): Add `vim-doge`

---

lua/astrocommunity/pack/vue/init.lua

Now this latest version should be, tsserver supports vue, then enable hybridMode, volar provides the template prompt.

fix(vue):  properly configure hybrid mode

---

lua/astrocommunity/code-runner/conjure/init.lua

Attempting to match list here: https://github.com/Olical/conjure/blob/934687860a71d1d03e569ce11f880a4d404e69aa/fnl/conjure/config.fnl#L56
This PR adds additional filetypes to activate the Conjure plugin

fix(conjure): Add missing filetypes

---

lua/astrocommunity/pack/just/init.lua

The just pack was create a while ago, when nvim-treesitter didn't yet have support for the syntax. However, this support has now been added (and it's been there for quite a while), so there's no reason to add it manually.
Additionally, it turns out the build instructions here are actually wrong, as the repo doesn't contain the `scanner.cc` file anymore, so using the pack actually causes an error when attempting to install the parser. (How did no one notice this? lol):
```
Downloading tree-sitter-just...                                                                         
Creating temporary directory                                                                            
Extracting tree-sitter-just... …
```

fix(just): use native treesitter parser

---

lua/astrocommunity/pack/nix/init.lua

In 44e8c959bb66a76a98efee588fe7bc56b8ecf754 an isssue with trying to install nixd via mason was fixed, by removing nixd from required mason packages and instead adding it as a required dependency for the pack, that should be present in the PATH.
However, normally, mason would've also registered nixd to lspconfig, but since mason isn't being used, nixd LSP was never registered, making this requirement pointless.
This actually registers nixd languge server through astrolsp plugin.

fix(nix): Actually use nixd LSP

---

lua/astrocommunity/diagnostics/trouble-nvim/init.lua

This is to avoid clashes with the [recent addition of `<Leader>x` to AstroNvim](https://github.com/AstroNvim/AstroNvim/commit/99c2b13df7b4943b3f82ca772db3dfb8f13f42e7).
This PR has also simplified some mapping descriptions.

fix(trouble-nvim): prevent clashes with existing `<Leader>x` mappings

---

lua/astrocommunity/pack/rust/README.md
lua/astrocommunity/pack/rust/init.lua

Closes #1109
Removes the opinionated `rust-analyzer` configuration except `cargo check` -> `cargo clippy`

feat(pack): remove opinionated config from `rust` pack

---

lua/astrocommunity/test/vim-test/README.md
lua/astrocommunity/test/vim-test/init.lua

Add support for vim-test which out of the box a wide range of languages, https://github.com/vim-test/vim-test?tab=readme-ov-file#features
I've kept these since they seem like _reasonable defaults_ but I am happy to remove these
```
vim.g["test#strategy"] = "neovim"
vim.g["test#neovim#term_position"] = "vert"
```

feat(test): add vim-test

---

lua/astrocommunity/git/octo-nvim/init.lua

The command registered for listing the changed files should use `Octo pr changes`, instead of listing the commits with `Octo pr commits`.

fix(git): Change command used for listing changed files in PR to the correct one. 

---

lua/astrocommunity/pack/laravel/README.md
lua/astrocommunity/pack/laravel/init.lua

Closes #1103 
Add support for laravel.nvim with some mappings

feat(pack): add laravel.nvim

---

lua/astrocommunity/editing-support/conform-nvim/init.lua

This PR fixes conform not falling back to the LSP for formatting introduced by 876032f. The last commit contains a typo, the proper name for the lsp option is `lsp_format`.
Currently the default config is "never", so formatting does not work if the LSP is the only formatter available.

fix(conform-nvim): fix bug caused by wrongly typed opt

---

lua/astrocommunity/media/codesnap-nvim/README.md
lua/astrocommunity/media/codesnap-nvim/init.lua

This plugin at least on the latest version doesn't support windows by any means but the "0.0.x" version does however but it's not so performant and works kinda differently 
This PR make sures that windows users get the latest working version that supports their OS

feat(codesnap-nvim): support for windows users

---

lua/astrocommunity/colorscheme/catppuccin/init.lua
lua/astrocommunity/split-and-window/colorful-winsep-nvim/README.md
lua/astrocommunity/split-and-window/colorful-winsep-nvim/init.lua

This plugin adds beautiful colors to the borders of your split windows. Additionally, it includes a smooth and pleasant animation when switching between them.
This PR also adds colorful-winsep.nvim integration to the catppuccin colorscheme
_Note_: For some reason, the integration doesn't work when specified as an optional spec, so I had to include it in the Catppuccin plugin specification.

feat(split-and-window): add colorful-winsep.nvim plugin

---

lua/astrocommunity/pack/haskell/README.md
lua/astrocommunity/pack/haskell/init.lua

This updates to the new [haskell-tools v4 release](https://github.com/mrcjkb/haskell-tools.nvim/releases/tag/4.0.0). This drops support for neovim v0.9. To add backwards compatibility I simply copied the entired of the spec. This protects against if the `opts` change between the two or something the previous version will always be correct.

feat(haskell): update `haskell-tools` to v4

---

lua/astrocommunity/pack/rust/README.md
lua/astrocommunity/pack/rust/init.lua

This updates to the new [Rustaceanvim v5 release](https://github.com/mrcjkb/rustaceanvim/releases/tag/5.0.0). This drops support for neovim v0.9. To add backwards compatibility I simply copied the entired of the spec. This protects against if the `opts` change between the two or something the previous version will always be correct.

feat(rust): update `rustaceanvim` to v5

---

lua/astrocommunity/media/cord-nvim/init.lua

fix(cord-nvim): Make build command cross-platform

---

lua/astrocommunity/debugging/nvim-bqf/README.md
lua/astrocommunity/debugging/nvim-bqf/init.lua
lua/astrocommunity/quickfix/nvim-bqf/README.md
lua/astrocommunity/quickfix/nvim-bqf/init.lua
lua/astrocommunity/quickfix/quicker-nvim/README.md
lua/astrocommunity/quickfix/quicker-nvim/init.lua

This adds the new [`quicker.nvim`](https://github.com/stevearc/quicker.nvim) plugin by the legendary `stevearc`
This also makes a new category `quickfix` since `debugging` isn't super clear. It deprecates the old `nvim-bqf` location and warns the user to migrate their configuration so it's non-breaking atm.

feat(debugging): add `quicker.nvim`

---

lua/astrocommunity/color/transparent-nvim/init.lua

This makes `transparent.nvim` actually work with Heirline now that features have been added that allow it to support it. This also fixes the fact that the `transparent.nvim` spec apparently wasn't using the `opts` table. So it's actually configurable by the user now.

fix(transparent-nvim): make `transparent.nvim` actually work with Heirline (also makes the `opts` table work as well)

---

lua/astrocommunity/pack/typst/init.lua

New releases of this plugin is quite frequent now (https://github.com/chomosuke/typst-preview.nvim/releases), so I don't think we should limit ourselves to `0.1.*`.
N/A

feat(pack): remove pinned version of `typst-preview.nvim` in `typst` pack

---

lua/astrocommunity/search/grug-far-nvim/init.lua

Additional options that should be set for grug-far.nvim if icons are disabled.
- https://github.com/MagicDuck/grug-far.nvim/blob/main/lua/grug-far/opts.lua#L150-L150
- https://github.com/MagicDuck/grug-far.nvim/blob/main/lua/grug-far/opts.lua#L156-L170
Before:
After:

fix(grug-far-nvim): fix icon disabled options

---

lua/astrocommunity/pack/go/README.md
lua/astrocommunity/pack/go/init.lua

This supersedes #1162. `gopls` uses `gofumpt` for formatting so we can leverage that after running `goimports`

fix(go): install missing `goimports`

---

lua/astrocommunity/pack/go/README.md
lua/astrocommunity/pack/go/init.lua

Enables `gofumpt` over `go fmt`

fix(go): enable `gofumpt` in `gopls` by default

---

lua/astrocommunity/color/tint-nvim/init.lua

In the `highlight_ignore_patterns`, `neo-tree` wasn't working at all, so I tried `NeoTree`. That worked except for the icons still dim. That's an acceptable limitation for now IMO. Perhaps in the future we can fix it so the icon hl group doesn't dim, either. But this is less broken than it was.

fix(tint-nvim): update neo-tree → NeoTree (ignore_patterns)

---

lua/astrocommunity/docker/lazydocker/README.md
lua/astrocommunity/docker/lazydocker/init.lua

Adds [Lazy Docker](https://github.com/mgierada/lazydocker.nvim) package to the AstroNvim community.
This PR adds a new shortcut to `Leader + t` + `d` which runs the Lazy Docker plugin.
It depends only on [lazydocker.nvim](https://github.com/mgierada/lazydocker.nvim) and it uses built-in ToggleTerm support.
No breaking changes or old behavior interference.

feat(docker): Add `lazydocker.nvim`

---

lua/astrocommunity/init.lua
lua/astrocommunity/pack/ansible/init.lua
lua/astrocommunity/pack/helm/init.lua

This PR improves filetype detection for helm files.
The current filetype detection often enables yaml-ls for helm templates. yaml-ls then marks helm specific syntax as errors. To avoid this, a few specific rules are added to detect helm files.
The new code is mainly based on the following sources:
- https://github.com/mandos/nvim-helm/blob/7b5b5945bf9c84b17dceb2f9a6cabfac7a6d12f1/lua/helm/init.lua
- https://github.com/mandos/nvim-helm/blob/7b5b5945bf9c84b17dceb2f9a6cabfac7a6d12f1/lua/helm/utils.lua
They are under the MIT license. How should I attribute them?

fix(helm): better file type detection

---

lua/astrocommunity/test/nvim-coverage/init.lua

Add mappings to `nvim-coverage`.
Also, it was added the option to reload the coverage report if it changes, a useful option complemented with the ease to show the coverage added with the mappings.
The mapping was added as a second layer behind `Tests` map. This is because `neotest` and `vim-test` use the `<Leader>T` map and name it like that, allowing to complement the usage of those plugins without depending on it.

feat(nvim-coverage): add keybindings

---

lua/astrocommunity/markdown-and-latex/markdown-preview-nvim/README.md
lua/astrocommunity/markdown-and-latex/markdown-preview-nvim/init.lua

Fix the installation process of `markdown-preview-nvim`.
This PR uses the recommendations given in the [comment](https://github.com/iamcco/markdown-preview.nvim/issues/690#issuecomment-2254280534) related with the reported issue about installing the plugin using `lazy.nvim`.
The plugin [Markdown Preview](https://github.com/iamcco/markdown-preview.nvim) seems to be unmaintained and the installation process provided in his documentation [fails when installed through `lazy.nvim`](https://github.com/iamcco/markdown-preview.nvim/issues/690).
Also, I added the variable `COREPACK_ENABLE_AUTO_PIN=0` to avoid the modification of the `package.json` ([described here](https://github.com/nodejs/corepack/blob/main/README.md#environment-variables)) used by the plugin, in case the user is using …

fix(markdown-preview-nvim): build using yarn when possible

---

lua/astrocommunity/pack/typescript/README.md
lua/astrocommunity/pack/typescript/init.lua

In `typescript` pack, add support for [`neotest-jest`](https://github.com/nvim-neotest/neotest-jest) if [`neotest`](https://github.com/nvim-neotest/neotest) is installed.
The usage of `table#insert` function allows to use the same pattern in other language packs without overriding the values (e.g.: use `rustaceanvim` integration for `neotest` in the same `neovim` configuration).
This usage was inspired from the `rust` [language pack](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/rust/init.lua#L83-L91).

feat(typescript): add neotest-jest support

---

lua/astrocommunity/icon/mini-icons/init.lua

This adds support for the new icon provider feature added into neo-tree.nvim (https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1527). This is currently unreleased but I tested it and it doesn't cause any problems being present in older versions and will just start working when neo-tree gets a new release tagged sometime next week.

feat(mini-icons): add `neo-tree.nvim` integration

---

lua/astrocommunity/test/neotest/init.lua

Add mappings to simplify the usage of watch-related commands when using `neotest`.
It also refactor the keybindings to follow current standards using an `opts` function instead of a table.
The API for the usage of `neotest.watch.stop()` is not well defined in terms of the type information for the usage.
This creates the necessity to use `@diagnostic disable-next-line: missing-parameter`.
For a closer look, see https://github.com/nvim-neotest/neotest/blob/master/doc/neotest.txt#L626

feat(neotest): add watch keybindings

---

lua/astrocommunity/pack/tailwindcss/init.lua

See also https://github.com/AstroNvim/astrocommunity/pull/915
Phoenix projects put the tailwind.config.js file in the root /assets folder. The addition of specific root dir detection in #912 broke the elixir-phoenix pack.

fix(tailwindcss): fix TailwindCSS pack not loading in Phoenix projects

---

lua/astrocommunity/completion/copilot-cmp/init.lua

Lazy load `copilot-cmp` when entering a file, not at the startup.

feat(copilot-cmp): load when opening a file

---

lua/astrocommunity/docker/lazydocker/init.lua

Add lazy loading to `lazydocker.nvim`. This way, it will only loads when the user request it via `<Leader>td`.
This improves the overall startup time of `Neovim`, but increase the perceived startup time of `lazydocker.nvim`.

feat(lazydocker): load when required only

---

lua/astrocommunity/remote-development/remote-sshfs-nvim/init.lua

For now keybinding \<Leader>ff and \<Leader>fw stops to work properly with remote-sshfs-plugin, when there is no ssh connection.
This happens, because the value of functions checks in the condition instead of call result.
Fixed the issue with calling this function :)

fix(remote-sshfs-nvim): use function call result

---

lua/astrocommunity/completion/avante-nvim/init.lua

Avante will now provide Plug mapping instead of commands for some functionalities to avoid poluting namespace from users.

fix(avante-nvim): update correct plug mappings

---

lua/astrocommunity/pack/harper/README.md
lua/astrocommunity/pack/harper/init.lua

Add [`harper-ls`](https://github.com/elijah-potter/harper/tree/master/harper-ls) integration, a `LSP` to interop with [Harper](https://writewithharper.com).
From it's website:
> Harper is an English grammar checker designed to be just right. You can think of it as an open-source alternative to Grammarly.

feat(pack): add Harper 

---

lua/astrocommunity/search/grug-far-nvim/init.lua

This does a major refactor on the `grug-far.nvim` spec that adds a lot more bindings and options for searching and replacing. It also aligns the recommended keymaps with what we have been using for `spectre.nvim` which is a very nice workflow.

feat(grug-far-nvim)!: add more features and align with recommended `spectre.nvim` mappings

---

lua/astrocommunity/pack/go/README.md
lua/astrocommunity/pack/go/init.lua

The PR adds [golangcilint](https://github.com/golangci/golangci-lint) as the default linter for go.pack. Currently no linters as part for the pack.

feat(go): Add golangcilint as default linter

---

lua/astrocommunity/pack/go/README.md
lua/astrocommunity/pack/go/init.lua

2467e24 'feat(go): Add golangcilint as default linter (#1213)'

revert(go): remove golangcilint as default linter

---

lua/astrocommunity/editing-support/copilotchat-nvim/init.lua

With this PR it is possible to define the prefix for CopilotChat.nvim via `AstroNvim/astrocore` `opts.options.g.copilot_chat_prefix` or if not defined use `<leader>P` as default.

fix(copilotchat-nvim): use custom prefix from astro core if defined

---

lua/astrocommunity/motion/tabout-nvim/init.lua

This cleans up the `tabout.nvim` spec to make sure it doesn't require `nvim-cmp` and also adds support for native vim snippets integration

fix(tabout-nvim): make `nvim-cmp` optional and add support for `vim.snippet`

---

lua/astrocommunity/pack/moonbit/README.md
lua/astrocommunity/pack/moonbit/init.lua

This adds support for the moonbit programming language

feat(pack): add Moonbit language support

---

lua/astrocommunity/pack/vue/init.lua

Fixed a typo in the package name that was causing an error
```lua
Error executing vim.schedule lua callback: ...al/nvim-data/lazy/mason.nvim/lua/mason-registry/init.lua:80: Cannot find package "vue-language-sever".
```
The error occurs when installing the package : ***"astrocommunity.pack.vue"***

fix(vue): correct typo in vue-language-server

---

lua/astrocommunity/pack/cpp/init.lua

Fix tbl extend on opts.config instead of opts
I believe this was a typo because assigning opts.config to a modified table of opts doesn't make sense

fix(cpp): tbl extend on opts.config instead of opts

---

lua/astrocommunity/diagnostics/lsp_lines-nvim/init.lua

enabled plugin causes diagnostics duplication and looks horrible IMO
before:
after:

fix(lsp_lines-nvim): disable plugin in `lazy` UI

---

lua/astrocommunity/pack/nvchad-ui/README.md
lua/astrocommunity/pack/nvchad-ui/init.lua

Add a pack for integrating the NvChad UI toolkit in AstroNvim

feat(pack): add an NvChad UI pack

---

lua/astrocommunity/note-taking/neorg/init.lua

With default workspace, Neorg can start with that workspace. The user does not have to run the command to load the workspace after starting nvim.

fix(neorg): Add default workspace for Neorg

---

lua/astrocommunity/completion/magazine-nvim/README.md
lua/astrocommunity/completion/magazine-nvim/init.lua

Adds [magazine.nvim](https://github.com/iguanacucumber/magazine.nvim), This replaces nvim-cmp and acts as a "beta" with performance and feature improvements before they get up streamed.

feat(completion): add magazine.nvim

---

lua/astrocommunity/completion/blink-cmp/README.md
lua/astrocommunity/completion/blink-cmp/init.lua

This adds a the new completion plugin [`blink.cmp`](https://github.com/Saghen/blink.cmp)

feat(completion): add `blink.cmp`

---

lua/astrocommunity/pack/typst/README.md
lua/astrocommunity/pack/typst/init.lua

With this PR, `typst_lsp` in the `typst` pack is replaced by `tinymist`. 
[`tinymist`](https://github.com/Myriad-Dreamin/tinymist) is a more actively-developed language server for the Typst language. Since https://github.com/typst/typst/pull/5193, `tinymist` has replaced `typst_lsp` to become the recommended LSP implementation in Typst's official docs.
Also, with this change, the user can now directly use the Mason-installed `tinymist` as the preview backend in `chomosuke/typst-preview.nvim`, without having to separately install a `typst-preview` server, thanks to the fact that this functionality has recently been successfully integrated into `tinymist` itself.
Tested locally (since over 5 months ago) with the following override:
```lua
{
"williamboman/mason-lspconfig.nvim",
opts = …
```

feat(pack): replace `typst_lsp` with `tinymist` in `typst` pack

---

lua/astrocommunity/editing-support/auto-save-nvim/README.md
lua/astrocommunity/editing-support/auto-save-nvim/init.lua

Closes #1233
Updates to use actively maintained okuuva repo, I also needed to update the way the callbacks work. These are currently broken since it's using autoformat_enabled instead of autoformat

feat(auto-save-nvim)!: swap to okuuva repo

---

lua/astrocommunity/lsp/nvim-lint/init.lua

make `nvim-lint` autocmd events(`"BufWritePost", "BufReadPost", "InsertLeave", "TextChanged"` now) can be configured from `opts.events`

feat(nvim-lint): make autocmd events configurable

---

lua/astrocommunity/pack/full-dadbod/init.lua

also, have dadbod use nerd fonts. be case insensitive
add pg to completion which is a file type used for sql tests

feat(full-dadbod): Improve lazy loading

---

lua/astrocommunity/diagnostics/tiny-inline-diagnostic-nvim/README.md
lua/astrocommunity/diagnostics/tiny-inline-diagnostic-nvim/init.lua

Adds [tiny-inline-diagnostic.nvim](https://github.com/rachartier/tiny-inline-diagnostic.nvim)
This sets the Astrocore diagnostic to level 2, this is prevent two sets of diagnostic info but will still have the icon in the column.

feat(diagnostics): add `tiny-inline-diagnostic-nvim`

---

lua/astrocommunity/pack/cs-omnisharp/README.md
lua/astrocommunity/pack/cs-omnisharp/init.lua

This PR adds C# language support with `omnisharp` as LSP

feat(pack): add csharp support with `omnisharp`

---

lua/astrocommunity/pack/moonbit/README.md
lua/astrocommunity/pack/moonbit/init.lua

This PR enables neotest support for the MoonBit language, as implemented in the following PR:
- https://github.com/moonbit-community/moonbit.nvim/pull/10
Tested locally with the same override spec without any issues.

feat(pack): add `neotest` integration to the `moonbit` pack

---

lua/astrocommunity/pack/harper/init.lua

According to https://github.com/williamboman/mason-lspconfig.nvim, the correct identifier for this language server in `mason-lspconfig` is `harper_ls`, not `harper-ls`.

fix(harper): fix typo in `harper`'s `mason-lspconfig` override

---

lua/astrocommunity/pack/proto/README.md
lua/astrocommunity/pack/proto/init.lua

Update language server references from `bufls` to `buf_ls` as `bufls` is deprecated and will be removed in lspconfig 0.2.1.

fix(proto): replace deprecated `bufls` with `buf_ls`

---

lua/astrocommunity/pack/ansible/README.md
lua/astrocommunity/pack/ansible/init.lua

This PR further extends the regex used to match common Ansible paths, [some of them are documented best practices, even](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable):
We're adding the following paths to the regex:
- ansible/
- playbooks/
- group_vars/
- host_vars/
- vars/
- tasks/
Here's an example on how nested variables look like in the wild:
```
├── ansible
│   ├── group_vars
│   ├── host_vars
│   ├── roles
│   │   ├── foo
│   │   │   ├── defaults
│   │   │   ├── tasks
│   │   │   └── vars
│   │   ├── bar
│   │   │   ├── defaults
│   │   │   ├── tasks
│   │   │   ├── templates
│   │   │   └── vars
│   │   └── baz
│   │       ├── vars
│   │       ├── defaults
│   │       └── tasks
│   └── vars
└── …
```

fix(pack): Add support for additional Ansible directory structures in `ansible`'s path_regex, and correct docs

---

lua/astrocommunity/completion/blink-cmp/init.lua

Ensure cmp-git is no longer enabled.

feat(blink-cmp): disable cmp-git

---

lua/astrocommunity/editing-support/copilotchat-nvim/init.lua

Closes #1291
Updates to v3 and removes the opts window changes as they have issues with window resizing and other issues when trying to move buffers around
They've updated the prompt actions
https://github.com/CopilotC-Nvim/CopilotChat.nvim/compare/v2.16.0...v3.0.0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L120-L128
`help_actions` was deprecated and now just uses prompt actions
https://github.com/CopilotC-Nvim/CopilotChat.nvim/compare/v2.16.0...v3.0.0#diff-48b86e8f407d8316ff351556d1495ecbe87b72a450d19713b83829c5165eba37R10-R12
I've removed the opts windows setting since they are too personal and was causing issues. people can add it into their own configs
```lua
window = {
layout = "float",
width = 74, -- absolute width in columns
height = vim.o.lines - 4, -- …
```

feat(copilotchat-nvim)!: update to v3

---

lua/astrocommunity/motion/leap-nvim/init.lua

Closes #1219 
The workaround breaks on 0.10+ so I've made it only apply when the minor version is less than 10.

fix(leap-nvim): Fix cursor invisible bug on nvim 0.10+

---

lua/astrocommunity/completion/blink-cmp/README.md
lua/astrocommunity/completion/blink-cmp/init.lua

This supersedes #1294.
`blink.cmp` is about to have a ton of breaking changes in their next release. This gets ahead of this while also updating some breaking changes that have already happened. Currently this runs the latest `main` of `blink.cmp` which requires `cargo` to be installed so that the core binaries can be built. This reliance on `cargo` will be dropped once a stable release is made

fix(blink-cmp)!: use the new blink version

---

lua/astrocommunity/pack/cs-omnisharp/init.lua
lua/astrocommunity/pack/cs/init.lua

Adds `csharpier` formatter registration when `conform` is used as formatter plugin.

feat(pack): add conform csharpier registrations to `cs` and `cs-omnisharp`

---

docs/assets/template.html5

Forgot about the leading path in github pages `/astrocommunity/` so we need to add a dot to the font preload to avoid flash of unstyled text.

docs: fix relative font path

---

lua/astrocommunity/snippet/mini-snippets/README.md
lua/astrocommunity/snippet/mini-snippets/init.lua

This adds [`mini.snippets`](https://github.com/echasnovski/mini.snippets) as an option for configuring snippets with a fairly fully featured configuration and integration setup.

feat(snippet): add `mini.snippets`

---

lua/astrocommunity/pack/laravel/init.lua

```
Failed to run `config` for laravel.nvim
.../.local/share/nvim/lazy/laravel.nvim/lua/laravel/app.lua:179: Promise-async is required for Laravel, please install it
- /laravel.nvim/lua/laravel/app.lua:179 _in_ **validate_instalation**
- /laravel.nvim/lua/laravel/app.lua:158 _in_ **start**
- /laravel.nvim/lua/laravel/init.lua:6 _in_ **setup**
```
Copied deps from https://adalessa.github.io/laravel-nvim-docs/docs/getting-started/

fix(pack): update `laravel-nvim` required deps from v2 to v3

---

lua/astrocommunity/completion/avante-nvim/init.lua

`render-markdown-nvim` need `file_types` parameter, but provide `filetypes`.just change `filetypes` to `file_types`
```lua
{
-- make sure `Avante` is added as a filetype
"MeanderingProgrammer/render-markdown.nvim",
optional = true,
opts = function(_, opts)
if not opts.file_types then opts.filetypes = { "markdown" } end
opts.file_types = require("astrocore").list_insert_unique(opts.file_types, { "Avante" })
end,
},
```

fix(avante-nvim): fix typo in opts

---

lua/astrocommunity/pack/docker/init.lua

Closes #1309 
This should turn off the default formatter from the docker_compose_language_service and use the one specified in the YAML pack to keep it all uniform and prevent double formatting if both packs are used at the same time. I encountered this issue with double formatting, which caused the code to jump up and down near the networks section.
[Screencast_20250105_205931.webm](https://github.com/user-attachments/assets/708e6d41-8e16-4ee9-a510-254ef3c11c92)
Maybe there is a better way. Feedback is welcome. 🙂

fix(docker): use default formatter for yaml and turn off from docker_compose_language_service 

---

lua/astrocommunity/debugging/nvim-dap-view/README.md
lua/astrocommunity/debugging/nvim-dap-view/init.lua

This adds the new [`nvim-dap-view`](https://github.com/igorlfs/nvim-dap-view) plugin which is a minimalistic alternative to `nvim-dap-ui`.

feat(debugging): add `nvim-dap-view`

---

lua/astrocommunity/fuzzy-finder/snacks-picker/README.md
lua/astrocommunity/fuzzy-finder/snacks-picker/init.lua

This adds the new picker from `snacks.nvim`: https://github.com/folke/snacks.nvim/blob/main/docs/picker.md

feat(fuzzy-finder): add `snacks.picker` from `snacks.nvim`

---

lua/astrocommunity/media/cord-nvim/init.lua

Pins `cord.nvim` to version `1.0.0` or newer.  
This is a precautionary measure in case Cord v2 is merged into the master branch *while* #1322 is not yet merged into astrocommunity, potentially causing unexpected errors.

chore(cord-nvim): pin version to v1

---

lua/astrocommunity/fuzzy-finder/fzf-lua/init.lua

I’ve added some key mappings to make all pickers more or less the same way. So, telescope, snacks-picker, and fzf-lua would have the same behavior.
I've copied the configuration from https://github.com/ibhagwan/fzf-lua/blob/8af88e542d70ed397f297a81168be0dd3394b0d4/lua/fzf-lua/profiles/telescope.lua#L60-L71

feat(fzf-lua): add key mappings similar to telescope

---

lua/astrocommunity/fuzzy-finder/fzf-lua/init.lua

This will add behavior similar to telescope and snacks-picker, where if there is a single result then it directly goes there instead of opening the picker window.
https://github.com/ibhagwan/fzf-lua/wiki#lsp-jump-to-location-for-single-result

feat(fzf-lua): directly go to definition when only a single result

---

lua/astrocommunity/media/cord-nvim/README.md
lua/astrocommunity/media/cord-nvim/init.lua

[`cord.nvim`](https://github.com/vyfor/cord.nvim) has been completely rewritten from the ground up, with a plethora of new features and updates. These changes may not be fully compatible with the previous version of the plugin. After extensive testing, the new version has proven stable, and we plan to merge the v2 branch on *February 1, 2025*.
With v2, the plugin now follows semantic versioning. Additionally, the Rust compiler is no longer required to install the plugin, as the server component can now be easily downloaded via GitHub Releases using the async `:Cord update` command.
- The minimum required Neovim version is bumped from `0.5.0` to `0.6.0`. This is unlikely to affect AstroNvim users, as it already requires a much more recent version.
- A [migration …

feat(cord-nvim)!: update to v2

---

lua/astrocommunity/pack/bash/init.lua

Not sure if this is correct, but nvim-lint seemed to have been missing, and also shellcheck wasn't set in conform, as it was for none-ls.

fix(bash): add nvim-lint and add shellcheck to conform

---

lua/astrocommunity/markdown-and-latex/markview-nvim/init.lua

Adapted config to consider breaking changes introduced in `markview.nvim` v25.1.
This fix works for `markview.nvim` v25.1 and later.

fix(markview-nvim): adapted config to consider breaking changes in version v25.1.

---

lua/astrocommunity/editing-support/conform-nvim/init.lua

Closes https://github.com/AstroNvim/astrocommunity/issues/1335
Adds a mapping `<Leader>lc` for ConformInfo, similar to nonels info.
Can't use same `<Leader>lI` since it's still occupied.

feat(conform-nvim): add mapping for ConformInfo

---

lua/astrocommunity/pack/nix/README.md
lua/astrocommunity/pack/nix/init.lua

nixd already provides formatting builtin:
https://github.com/nix-community/nixd/blob/2c25600cb9c91bc06fe8676c044814dc30435274/nixd/docs/configuration.md?plain=1#L62

fix(nix): drop none-ls formatter

---

lua/astrocommunity/pack/docker/init.lua

Hadolint doesn't work with docker compose, only dockerfile.
Use same ft as in none-ls: https://github.com/nvimtools/none-ls.nvim/blob/main/doc/BUILTINS.md#defaults-44

fix(docker): use dockerfile ft for hadolint

---

lua/astrocommunity/completion/copilot-lua-cmp/README.md
lua/astrocommunity/completion/copilot-lua-cmp/init.lua

This should hopefully add similar copilot support to blink as it was for cmp. Not sure if it's 1 to 1, since I'm not familiar with either of them :see_no_evil: 
I've checked https://cmp.saghen.dev/configuration/keymap.html#example and copied `Tab` from main community pack.

feat(copilot-lua-cmp): add blink.cmp support

---

lua/astrocommunity/neovim-lua-development/lazydev-nvim/README.md
lua/astrocommunity/neovim-lua-development/lazydev-nvim/init.lua

Deprecate the plugin, since it's been part of the core since v4.22.0
Deprecation setup copied from https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/project/neoconf-nvim

fix(lazydev-nvim): add deprecation notice as it was added upstream

---

lua/astrocommunity/editing-support/copilotchat-nvim/init.lua

This is an attempt to further improve on https://github.com/AstroNvim/astrocommunity/pull/1333.
First, a separate function to check for the currently active pickers name or `nil` if it has no CopilotChat.integrations module. Since I did not find a better solution to check if snacks.nvim picker is actually used as the picker (solely checking for snacks.nvim availability does not mean that it's picker is actually configured and used, contrary to telescope or fzf-lua), I tried finding something to find out, which is up for debate. Second, the `create_mapping()` function now checks for availability and compatibility of the active picker with CopilotChat integrations and gracefully warn users if it's not.

refactor(copilotchat-nvim): improve picker selection logic and error handling

---

lua/astrocommunity/fuzzy-finder/fzf-lua/init.lua

This change should match what the telescope and snacks-picker do: search for diagnostics for the whole workspace instead of the current buffer.

fix(fzf-lua): show diagnostics for whole workspace

---

lua/astrocommunity/pack/rust/init.lua

Added a `rustaceanvim` opt (`load_rust_types`) to make sure rust types are loaded into lldb.
Recently codelldb dropped support for rust types to be passed to LLDB. This is okay as the rust toolchain supports feature of loading rust types into lldb.
Tested on ubuntu and MacOS.
Before:
After:
Reference: https://github.com/mrcjkb/rustaceanvim/issues/552#issuecomment-2455033130

fix(rust): rust types load in lldb

---

lua/astrocommunity/neovim-lua-development/lua-console-nvim/README.md
lua/astrocommunity/neovim-lua-development/lua-console-nvim/init.lua

[Lua-console.nvim](https://github.com/YaroSpace/lua-console.nvim) handy scratch pad / REPL / debug console for Lua development and Neovim exploration and configuration.

feat(neovim-lua-development): add lua-console.nvim

---

lua/astrocommunity/pack/chezmoi/init.lua

`fzf-lua` was defined outside of `specs`, causing none of the `specs` to load. 
Fixes https://github.com/AstroNvim/astrocommunity/issues/1269
Also enables auto-watching with notifications on apply.

feat(chezmoi): Fix `specs` loading and enable watch option

---

lua/astrocommunity/editing-support/quick-scope/README.md
lua/astrocommunity/editing-support/quick-scope/init.lua

This pr adds the unblevable/quick-scope vim plugin to astrocommunity.
It offers a visual enhancement to f and t motions. I quite like it as I find it less intrusive than plugins like sneak or flash and just improves on a default vim workflow.
I configured it to my liking to add a bit of value to its addition to astrocommunity.

feat(editing-support): Add `quick-scope`

---

lua/astrocommunity/file-explorer/mini-files/init.lua

Hello, I regularly use `mini.files` and I've noticed, in the default configuration provided by astrocommunity, we don't include keybindings for opening files in splits.
This PR addresses that.
NOTE: The code for `map_split` function was copied from [LazyVim's mini-files](https://github.com/LazyVim/LazyVim/blob/cb223553ff73eb2f37ffb5dc0bb75b76a4677faf/lua/lazyvim/plugins/extras/editor/mini-files.lua#L48)

feat(mini-files): add mappings for open in splits

---

docs/assets/template.html5

There seems to be an issue when compiling the templates which doesn't like the new `${}` string interpolation syntax. Should work now with normal concatenation.

docs(main): fix string interpolation

---

lua/astrocommunity/completion/copilot-vim-cmp/README.md
lua/astrocommunity/completion/copilot-vim-cmp/init.lua
lua/astrocommunity/completion/copilot-vim/README.md
lua/astrocommunity/completion/copilot-vim/init.lua

This will add the official GitHub Copilot vim plugin (from tpope) and cmp support. The main reason is because copilot.vim gets updated immediately to any Copilot changes.
There might be breaking changes or any other slowdowns in the copilot-lua similar to https://github.com/zbirenbaum/copilot.lua/pull/368 and it would be nice to have an alternative that's official and immediately updated by GitHub itself.

feat(completion): add copilot-vim-cmp

---

lua/astrocommunity/code-runner/mf-runner-nvim/README.md
lua/astrocommunity/code-runner/mf-runner-nvim/init.lua

This PR introduces [mf-runner.nvim](https://github.com/burgr033/mf-runner.nvim). A lightweight code runner plugin that uses good old Makefiles as a base.

feat(code-runner): Add mf-runner.nvim

---

lua/astrocommunity/search/grug-far-nvim/init.lua

This should add support for the new GrugFarWithin cmd and also add the missing copilot.vim options to disable it inside grug-far buffer.
Thanks to https://github.com/LazyVim/LazyVim/pull/5772

feat(grug-far-nvim): add support for GrugFarWithin

---

lua/astrocommunity/search/grug-far-nvim/init.lua

This PR works around the following plugin conflict...
- https://github.com/MagicDuck/grug-far.nvim/issues/419#issuecomment-2727111902
... by re-enabling `which-key` for `ft=grug-far` in `grug-far-nvim/init.lua`, as proposed by @magicduck (the project owner himself) in https://github.com/MagicDuck/grug-far.nvim/issues/419#issuecomment-2727111902:
> the config that @rami3l mentions is likely a hold over from "olden times" when which-key caused folds not to work correctly in grug-far, but that issue has been resolved for some time.
> [..]
> ```lua
>         if not opts.disable then opts.disable = {} end
>         opts.disable.ft = require("astrocore").list_insert_unique(opts.disable.ft, { "grug-far" })
> ```

fix(grug-far-nvim): re-enable `which-key` for `ft=grug-far`

---

lua/astrocommunity/completion/avante-nvim/init.lua

- Ensure all avante keybinds use the same prefix

feat(avante-nvim): consolidate keybinds under existing prefix

---

lua/astrocommunity/editing-support/mcphub-nvim/README.md
lua/astrocommunity/editing-support/mcphub-nvim/init.lua

Adds `mcphub.nvim`, with optional avante-nvim integration

feat(editing-support): Add mcphub.nvim 

---

lua/astrocommunity/completion/magazine-nvim/init.lua
lua/astrocommunity/utility/noice-nvim/init.lua

Closes #1403
With the plugin enabled you'll have both blink and nvim-cmp enable, I've just disabled blink

fix(magazine-nvim): not disabling blink

---

lua/astrocommunity/editing-support/yanky-nvim/init.lua

Fixes bug reported in https://github.com/AstroNvim/astrocommunity/issues/1405#issuecomment-2764361961

fix(yanky-nvim): Fix typo in command

---

lua/astrocommunity/debugging/nvim-dap-repl-highlights/init.lua

nvim-dap in dependencies breaks lazy loading of the nvim-dap plugin and all related plugins
before this patch dap* plugins loaded on nvim open:

fix(nvim-dap-repl-highlights): nvim-dap in dependencies breaks lazy loading

---

lua/astrocommunity/completion/blink-cmp-tmux/README.md
lua/astrocommunity/completion/blink-cmp-tmux/init.lua

Add blink-cmp-tmux
moving to blink

feat(completion): add blink-cmp-tmux

---

lua/astrocommunity/pack/rust/init.lua

Update to use v6 when 0.11 nvim is installed, I don't believe the other breaking changes effect us.
https://github.com/mrcjkb/rustaceanvim/releases/tag/v6.0.0

feat(pack)!: update rust pack to use v6 rustaceanvim when using 0.11 nvim

---

lua/astrocommunity/pack/rust/init.lua

Mason paths within a package are not really considered stable, so we should rely on stable paths if available. I have a PR open to resolve this stable path and then we can merge this in
Relies on https://github.com/mason-org/mason-registry/pull/9565

fix(rust): use a stable path for `codelldb` in Mason

---

lua/astrocommunity/completion/copilot-lua-cmp/init.lua

After migration to v5, when using this plugin, nvim-cmp is installed automatically, which does not necessarily need to happen if blink.cmp is installed
Old behavior after v5: plugin is enabled, nvim-cmp is installed automatically despite a valid completion engine (blink.cmp) being present
New behavior after v5: plugin is enabled, nvim-cmp is not set up unless already installed

fix(copilot-lua-cmp): make nvim-cmp optional

---

lua/astrocommunity/completion/copilot-cmp/init.lua

Without the change from this PR, loading `astrocommunity/completion/copilot-cmp` leads to the following error message at startup:
> ```
> Failed to run `config` for mini.icons
> 
> ...unity/lua/astrocommunity/completion/copilot-cmp/init.lua:59: attempt to index field 'symbol_map' (a nil value)
> 
> # stacktrace:
>   - /astrocommunity/lua/astrocommunity/completion/copilot-cmp/init.lua:59 _in_ **values**
>   - /astroui/lua/astroui/status/utils.lua:155 _in_ **icon_provider**
>   - /astroui/lua/astroui/status/hl.lua:41 _in_ **hl**
>   - /heirline.nvim/lua/heirline/statusline.lua:355 _in_ **_eval**
>   - /heirline.nvim/lua/heirline/statusline.lua:398 _in_ **_eval**
>   - /heirline.nvim/lua/heirline/statusline.lua:398 _in_ **_eval**
>   - /heirline.nvim/lua/heirline/statusline.lua:398 _in_ …
```

fix(copilot-cmp): add symbol_map initialization in mini.icons configuration

---

lua/astrocommunity/editing-support/nvim-treesitter-sexp/README.md
lua/astrocommunity/editing-support/nvim-treesitter-sexp/init.lua
lua/astrocommunity/pack/clojure/README.md

Disable nvim-treesitter-sexp plugin when running neovim 0.11 (errors due to treesitter breaking changes)
> If there is a preferred approach to managing breaking changes in plugins (that arent fixed yet), feel free to change this PR or help me know what I should change it too.  Thanks.
An [issue has been raised with the maintainer](https://github.com/PaterJason/nvim-treesitter-sexp/issues/12) of the package.
nvim-treesitter-sexp fails when using its commands for neovim 0.11 and AstroNvim v5
This plugin is failing due to breaking changes in treesitter since neovim 0.11

fix(editing-support): disable nvim-treesitter-sexp for neovim 0.11

---

lua/astrocommunity/completion/codeium-nvim/init.lua

This PR fixes an issue in the Codeium plugin's mini.icons configuration where it was trying to access `opts.symbol_map.codeium` without first checking if `opts.symbol_map` exists.
This fix prevents an error that would occur when `opts.symbol_map` is nil, similar to how it's already checked in the lspkind configuration above it.

fix(codeium-nvim): add symbol_map initialization in mini.icons configuration

---

lua/astrocommunity/git/neogit/init.lua

Added `<Leader>gnh`, `<Leader>gnv` and `<Leader>gnf` mappings for Neogit to open windows with different `kind` options values: `split`, `vsplit`, `float`.
Mappings are inspired by toggleterm mappings `<Leader>th`, `<Ledaer>tv` and `<Leader>tf`

feat(neogit): add mappings to open Neogit in floating window, horizontal and vertical splits

---

lua/astrocommunity/lsp/actions-preview-nvim/init.lua

The backend config option for `actions-preview.nvim` expects a table with a priority list of backends to attempt to use. This PR fixes the configuration

fix(actions-preview-nvim): fix incorrect picker backend configuration

---

lua/astrocommunity/editing-support/multiple-cursors-nvim/init.lua

Added icon for group `<leader>m` of mappings provided by this plugin.

feat(multiple-cursors-nvim): Add icon for mappings prefix

---

lua/astrocommunity/recipes/telescope-nvim-snacks/README.md
lua/astrocommunity/recipes/telescope-nvim-snacks/init.lua

Many plugins still rely on Telescope, but Snacks is now the default in AstroNvim. This config configures Telescope _without_ disabling Snacks.

feat(recipes): Add telescope + snacks plugin

---

lua/astrocommunity/utility/noice-nvim/init.lua

Since disabling lsp_progress in the statusline is hardcoded, it interferes with user-configured statuslines and is difficult to debug. We'll disable it temporarily.

fix(noice-nvim): don't override the lsp_progress component

---

lua/astrocommunity/pack/laravel/init.lua

It looks like the provided doc here is wrong https://adalessa.github.io/laravel-nvim-docs/docs/pickers/ and it should be nested under features like they show here https://adalessa.github.io/laravel-nvim-docs/docs/getting-started/
Currently, you get this
```
Error executing Lua callback: ...e/nvim/lazy/laravel.nvim/lua/laravel/pickers_manager.lua:30: Picker provider not found: telescope. Check your configuration
stack traceback:
[C]: in function 'error'
...e/nvim/lazy/laravel.nvim/lua/laravel/pickers_manager.lua:30: in function 'make'
.../.local/share/nvim/lazy/laravel.nvim/lua/laravel/app.lua:232: in function <.../.local/share/nvim/lazy/laravel.nvim/lua/laravel/app.lua:206>
vim/shared.lua: in function 'app'
...vel.nvim/lua/laravel/providers/user_command_provider.lua:35: in function …
```

fix(laravel): picker not getting defined correctly

---

lua/astrocommunity/editing-support/nvim-paredit/README.md
lua/astrocommunity/editing-support/nvim-paredit/init.lua

Adds the [julienvincent/nvim-paredit](https://github.com/julienvincent/nvim-paredit) plugin to provide structural editing support for Lisp dialects.
nvim-paredit plugin supports the changes in Neovim 0.11 and will be included in the Clojure pack in a future PR (once this PR has been approved)

feat(editing-support): add nvim-paredit plugin

---

lua/astrocommunity/editing-support/parpar-nvim/README.md
lua/astrocommunity/editing-support/parpar-nvim/init.lua

Plugin ensures nvim-paredit and nvim-parinfer work well together
Imports both plugins from astrocommunity rather than including the plugins as dependencies (please comment if this is not the correct approach)
Parpar provides the two common approaches in one plugin and ensures the plugins do not conflict with each other when editing.
Parpar can be imported into the Clojure pack and simplify its code (in a future PR)

feat(editing-support): add parpar-nvim plugin

---

lua/astrocommunity/editing-support/other-nvim/README.md
lua/astrocommunity/editing-support/other-nvim/init.lua

Add [rgroli/other.nvim](https://github.com/rgroli/other.nvim) to editing-support, including built-in languages and custom mappings for Clojure

feat(editing-support): add other-nvim

---

lua/astrocommunity/pack/clojure/README.md
lua/astrocommunity/pack/clojure/init.lua

Replace nvim-treesitter-sexp with parpar-nvim.
Add other-nvim to pack with clojure specific pattern matching.
nvim-treesitter-sexp fails on neovim 0.11
nvim-paredit is a drop-in replacement for nvim-treesitter-sexp that works with Neovim 0.10 & 0.11
parpar provides nvim-paredit and nvim-parinfer and ensures they work together
Other-nvim will be added in a future PR, once clojure mappings have been merged into the upstream project.

feat(clojure): update to use parpar-nvim

---

lua/astrocommunity/pack/bash/README.md
lua/astrocommunity/pack/bash/init.lua

While bashls doesn't officially support zsh, the syntax is almost the same and will get you most of the way there to make dealing with zsh files much better.

feat(bash): add zsh support

---

lua/astrocommunity/editing-support/other-nvim/README.md
lua/astrocommunity/editing-support/other-nvim/init.lua

Clojure support added to other.nvim via PR https://github.com/rgroli/other.nvim/pull/67
- Add clojure filetype to lazy
- Update readme

feat(other-nvim): clojure support added upstream

---

lua/astrocommunity/pack/typescript/README.md
lua/astrocommunity/pack/typescript/init.lua

This will remove html-css from typescript, so users can opt-in on their own.
Closes #1421
LazyVim doesn't even include Emmet, but we probably want to keep it, since VSCode has it and it's widely used during HTML dev.

refactor(typescript)!: remove html-css pack import

---

lua/astrocommunity/split-and-window/neominimap-nvim/init.lua

Closes https://github.com/AstroNvim/astrocommunity/issues/1476
Fixes the bug reported in https://github.com/AstroNvim/astrocommunity/issues/1476, while still supporting `opts`.
Summary: due to when neominimap.nvim looks at the config file, it means that setting the options in `config` doesn't actually work, instead it must be set during `init`.
This is similar to the minimum viable reproducible config, but instead using my version of astrocommunity :smile: 
```lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
-- bootstrap lazy
local …
```

fix(neominimap-nvim): set options within init instead of config

---

lua/astrocommunity/indent/indent-blankline-nvim/init.lua

Closes #1484
Use indent-blankline v3 main entry point
Refer to https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3

fix(indent-blankline-nvim): Use indent-blankline v3 main entry point

---

lua/astrocommunity/pack/purescript/init.lua

```
Error executing vim.schedule lua callback: ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:80: Cannot find package "purs-tidy".
stack traceback:
[C]: in function 'error'
...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:80: in function 'get_package'
...on-tool-installer.nvim/lua/mason-tool-installer/init.lua:180: in function 'callback'
...share/nvim/lazy/mason.nvim/lua/mason-core/async/init.lua:87: in function 'step'
...share/nvim/lazy/mason.nvim/lua/mason-core/async/init.lua:96: in function 'run'
...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:202: in function 'refresh'
...on-tool-installer.nvim/lua/mason-tool-installer/init.lua:262: in function ''
vim/_editor.lua: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```

fix(purescript): fix `error Cannot find package "purs-tidy"`

---

lua/astrocommunity/colorscheme/catppuccin/init.lua

Added `blink-cmp` support to catppuccin. `blink-cmp` is the default for AstroNvim currently, so the theme should support it.

fix(catppuccin): added blink cmp support

---

lua/astrocommunity/editing-support/multicursors-nvim/init.lua

Replaced deprecated 'smoka7/hydra.nvim' with the maintained 'nvimtools/hydra.nvim' to fix config crash related to invalid module loading.

fix(multicursors-nvim): update hydra dependency to official repo

---

lua/astrocommunity/motion/nvim-spider/init.lua

According to [README.md](https://github.com/chrisgrieser/nvim-spider?tab=readme-ov-file#utf-8-support), `luautf8` rocks package is required to correctly handle UTF-8 layouts (CJK, cyrillic, etc.).
Otherwise user won't be able to jump word-wise in layout other than english.
I added [luarocks.nvim](https://github.com/vhyrro/luarocks.nvim) dependency to install it.

fix(nvim-spider): provide UTF-8 support by default

---

lua/astrocommunity/pack/lua/README.md
lua/astrocommunity/pack/lua/init.lua

selene is not compatible with aarch64 (e.g., Raspberry Pi 5). This adds architecture detection to avoid installing selene where unsupported, while preserving all other functionality. This prevents constant failed installs on Nvim start when using Lua pack.
---
This pull request introduces conditional support for the `selene` linter based on the system architecture, specifically excluding it on `aarch64` systems. It also refactors related configurations to ensure compatibility and maintainability.
* Added a check for the system architecture (`aarch64`) using `vim.loop.os_uname().machine` and stored the result in a new `is_aarch64` variable. (`lua/astrocommunity/pack/lua/init.lua`, [lua/astrocommunity/pack/lua/init.luaR5-R22](diffhunk://#diff-f51ea87d5a049b1b100f6cee98c76196c2d47fb9deb55f670 …

fix(lua): skip selene install on aarch64 platforms

---

lua/astrocommunity/completion/codex-nvim/README.md
lua/astrocommunity/completion/codex-nvim/init.lua

This might be one of the case where we need to prefix the author to the name, since I recon it could be a flood of codex.nvim plugins. WDYT? @AstroNvim/astrocommunity-maintainers

feat(completion): Add in codex.nvim

---

lua/astrocommunity/pack/proto/init.lua

Replacing _buf-language-server_ to _buf_ls_ as _buf-language-server_ is deprecated.
p.s.
Need help to aprove this changes, cause I tried several time to uninstall _buf-language-server_ via mason ui, but every time it installs it again. I don't have any custom config's that installs _buf-language-server_. 
Cheers! :sparkles:

fix(proto): replace deprecated buf-language-server with buf_ls

---

lua/astrocommunity/editing-support/conform-nvim/init.lua

There was an issue where timeout was too short and often caused timeout warning, also it seems that it always fell back to 'never' instead of 'fallback' for lsp_format: https://github.com/stevearc/conform.nvim/blob/a4bb5d6c4ae6f32ab13114e62e70669fa67745b9/doc/conform.txt#L134-L147

fix(conform-nvim): use default timeout and explicit lsp_format

---

lua/astrocommunity/pack/proto/README.md
lua/astrocommunity/pack/proto/init.lua

#1505 replaced `buf-language-server` with `buf_ls`, but that's not the correct package name (see [here](https://github.com/mason-org/mason-registry/blob/main/packages/buf/package.yaml)).
Currently, the following import
```lua
{ import = "astrocommunity.pack.proto" },
```
results in:
```
Error executing vim.schedule lua callback: ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:32: Cannot find package "buf_ls".
stack traceback:
[C]: in function 'error'
...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:32: in function 'get_package'
...on-tool-installer.nvim/lua/mason-tool-installer/init.lua:196: in function 'callback'
...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:153: in function 'refresh'
...on-tool-installer.nvim/lua/mason-tool-installer/init.lua:271: in …
```

fix(proto): Remove invalid buf_ls package

---

lua/astrocommunity/pack/docker/init.lua

This was causing an issue because of overwriting what conform was setting here: https://github.com/AstroNvim/astrocommunity/blob/b69674df8de9a083754d44fb8a96d8dac1c06860/lua/astrocommunity/editing-support/conform-nvim/init.lua#L6 and enabling back the astrolsp formatting
Use filter instead: https://neovim.io/doc/user/lsp.html#vim.lsp.buf.format()

fix(docker): filter out docker compose filtering instead of disabling

---

lua/astrocommunity/completion/avante-nvim/init.lua

Scopes the `oa` neo tree mapping under the filesystem config to prevent `invalid mapping` warnings when viewing other sources (git, buffers, etc).

fix(avante-nvim): prevent neo-tree mapping warnings

---

lua/astrocommunity/lsp/dev-tools-nvim/README.md
lua/astrocommunity/lsp/dev-tools-nvim/init.lua

Add utility (LSP):
In-process LSP server of custom code actions, enhanced actions picker, community actions library and a convenient interface for customization and enhancement of your Neovim with custom code actions.

feat(lsp): added dev-tools.nvim

---

lua/astrocommunity/pack/nginx/README.md
lua/astrocommunity/pack/nginx/init.lua

Gonna daily drive this for a few days before I mark it as ready.

feat(pack): Add nginx pack

---

lua/astrocommunity/pack/ansible/init.lua

Closes #1523 
The current regex is leading to multiple false matches, because the keywords `hosts` and `tasks` are not exclusively used in ansible files.
Ansible playbooks have those keywords at the start of the line, so it's just easier to search for `^(hosts\\:tasks)`

fix(ansible): improve regex pattern to avoid false matches

---

lua/astrocommunity/completion/avante-nvim/init.lua

**`markview.nvim` Plugin Enhancements (Avante integration)**
* Added a defensive check for `opts.preview` to avoid potential `nil` dereferencing.
* Ensures compatibility and resilience when plugin options are partially defined.
* This update to `markview.nvim` ensures that the plugin doesn't fail if `opts.preview` is undefined, which may occur depending on other plugin configurations.

fix(avante-nvim): Check for nil value in opts table for markview.nvim dependency

---

lua/astrocommunity/editing-support/nvim-treesitter-context/init.lua

nvim-treesitter-context changed the user commands to a single `TSContext` cmd with subcommands `enable`/`disable`/`toggle`. This patch updates the plugin spec to reflect those changes

fix(nvim-treesitter-context): fix outdated commands

---

lua/astrocommunity/pack/json/init.lua

This solves a problem where lazy could not resolve dependency if it was already installed in user configuration (see video below)
https://github.com/user-attachments/assets/ab4a1bcb-119c-49ea-8027-74993fa3070e
split from #1542

fix(json): Normalize casing of schemastore plugin

---

lua/astrocommunity/snippet/nvim-snippets/init.lua

fix neogen and blink cmp option error when enable `astrocommunity.snippet.nvim-snippets`
Closes #1527
If I want to use neovim native snippet system, I found that neogen and the blink cmp option has errors.
add spec option in `astrocommunity.snippet.nvim-snippets`:
```lua
{
"Saghen/blink.cmp",
optional = true,
opts = { snippets = { preset = "default" } },
},
{
"danymat/neogen",
optional = true,
opts = { snippet_engine = "nvim" },
},
```

feat(nvim-snippets): add neogen and blink cmp integration

---

lua/astrocommunity/completion/nvim-cmp/init.lua

`opts.sources` may not be intialized when `table.insert(opts.sources, { name = "lazydev", group_index = 0 })` is called

fix(nvim-cmp): Check for nil value in opts table

---

lua/astrocommunity/pack/vue/init.lua

This should fix the issue with vue_ls not working due to required changes for the v3.
https://github.com/vuejs/language-tools/discussions/5456
https://github.com/vuejs/language-tools/wiki/Neovim

fix(vue): update config to support v3

---

lua/astrocommunity/pack/hurl/init.lua

This pull request updates the keymap description for the Hurl integration in AstroNvim. The description has been changed from **"HurlNvim"** to **"Hurl"** for improved clarity and alignment with the naming convention used throughout the pack.
This is a minor non-breaking change that improves the user experience by providing a more concise and recognizable label in the keymap list.
- **No breaking changes**
- **No new dependencies introduced**
- **This change improves visual consistency with other pack integrations and tool names**

chore(hurl): rename keymap description to "Hurl" 

---

lua/astrocommunity/markdown-and-latex/vimtex/init.lua

For some reason, two keymaps, `tsb` for toggling line break and `tss` for toggling starred environment, was missing in the which key descriptions in the old setting of `vimtex`. I added them.

fix(vimtex): add two missing `which-key` descriptions

---

lua/astrocommunity/pack/python/init.lua

- User might have a global `debugpy` installation, so we first check for `debugpy-adapter` before falling back to `python` 
- https://github.com/mfussenegger/nvim-dap-python/commit/261ce649d05bc455a29f9636dc03f8cdaa7e0e2c
- Only attempt to get `debugpy` package if Mason registry is available (since mason is optional and user might disable it)
N/A

refactor(python): make mason optional during dap-python setup

---

lua/astrocommunity/pack/oxlint/init.lua

Oxlint needs to be manually enabled until mason-lspconfig.nvim v2 is introduced in Astronvim v6.

fix(oxlint): enable oxlint in astrolsp

---

lua/astrocommunity/editing-support/copilotchat-nvim/README.md
lua/astrocommunity/editing-support/copilotchat-nvim/init.lua
lua/astrocommunity/editing-support/mcphub-nvim/init.lua

Release notes: https://github.com/CopilotC-Nvim/CopilotChat.nvim/releases/tag/v4.0.0
for summary
- copilot.lua/copilot.vim is no longer hard dependency
- mcphub.nvim now has proper integration with copilotchat
- some commands changed

feat(copilotchat-nvim): update to v4 and add mcphub.nvim integration

---

lua/astrocommunity/pack/sql/README.md
lua/astrocommunity/pack/sql/init.lua

The original configuration for `sqlfluff` add an extra `--dialect ansi` argument to the null_ls configuration, forcing the use of ANSI dialect. This is very annoying since it will override the dialect set in the configuration file `.sqlfluff` and leave little options for the user to use their desired dialect. With this change I remove that extra argument. However, this also means that the user must create a `.sqlfluff` file in the folder and specify the dialect there. I might adjust the README file to reflect this.

feat(sql)!: Dont force ansi dialect

---

lua/astrocommunity/markdown-and-latex/markdown-preview-nvim/init.lua

Use this new build command to build markdown-preview. Fix tslib module not found when npm is installed by [asdf](https://asdf-vm.com/).
Link to the author: https://github.com/iamcco/markdown-preview.nvim/issues/690#issuecomment-2782326124

fix(markdown-preview-nvim): Change build command to download prebuilt version of markdown-preview.

---

lua/astrocommunity/completion/copilot-lua-cmp/init.lua

Rebinds the dismiss keybinding to be <C-e> which is a common convention in vim/nvim to close a popup menu
Closes #1564

fix(copilot-lua-cmp): rebind dismiss keybinding to avoid keymap conflict
